### ISSUE TITLE
container re-created when it shouldn't

### ISSUE THREAD

**Issue by swingbit** [docker/compose#10068]
### Description

I'm experiencing an issue similar to #9600 and #9897, i.e. a container gets recreated needlessly.

`docker-compose.yml contains` 3 services:
- `tools` (depends on `api`)
- `api` (depends on `db`)
- `db`

At least once every day, a `docker-compose run tools` recreates the `api` container, while nothing has changed. Trying the same again does not recreate the `api` container.

Container images are very much static. They haven't been updated for weeks.

For now I cannot easily replicate this with a simple example, but the following is to my understanding good evidence that there is a bug. 

I started saving the result of this every day:
```
TS=$(date +%s)
docker-compose config > config.${TS}
docker-compose config --hash api > hash.${TS}
docker inspect api -f '{{json .Config.Labels}}' | jq > labels.${TS}
```

The result of the first two commands does not change across two days (with the container being recreated in between).
The result of the third one (the labels) does change:

```
# diff config.1670434754 config.1670766565
# diff hash.1670434754 hash.1670766565
# diff labels.1670434754 labels.1670766565
2c2
<   "com.docker.compose.config-hash": "e4c45cf84fe52b2e910b49746c2c6102067609eea52ede56cbe7d52d3dc76545",
---
>   "com.docker.compose.config-hash": "e38f8b5bff668614848f485f577db900a56eb031386c32bc996b6187b357e161",
```

So, the label says the hash has changed, but the hash hasn't changed!

### Compose Version

```Text
# docker-compose version
Docker Compose version v2.12.0

# docker compose version
Docker Compose version v2.12.0
```

### Docker Environment

```Text
# docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  compose: Docker Compose (Docker Inc., v2.12.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 16
 Server Version: 20.10.20
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.14.0-70.26.1.el9_0.x86_64
 Operating System: Rocky Linux 9.0 (Blue Onyx)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.34GiB
 Name: spinque94.gk.spinque.com
 ID: 27M4:ZWNY:D746:3FWT:P4K3:Q4W6:2RKI:NQF4:A5NI:OF75:NRS7:NT2A
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by swingbit** [comment]
It's worth mentioning that v2.16.0 behaves a lot worse than v2.12 or v2.14, i.e. containers are almost always recreated.
I'll test v2.17.0 asap.

**Comment by swingbit** [comment]
v2.17.0-rc1 is definitely much better than 2.16.0. I'll keep an eye on it for a couple of days.

**Comment by powerman** [comment]
Not sure is it same issue or not, but I noticed all containers are recreated without any config changes after server reboot. `docker compose stop && docker compose rm -f && docker compose up -d` fixes this.

**Comment by Programie** [comment]
The same happens to me as well.

Executing `docker compose up -d` always recreates all containers even if there is no change at all. I can reproduce the issue every time. I.e. executing `docker compose up -d` once again also recreates all the containers.

I'm using Compose v2.16.0 installed using the `docker-compose-plugin` package from the official Docker Debian repo on Debian Bullseye.

**Comment by cybermcm** [comment]
@Programie: You have to wait for the repo update or manual download the compose plugin and put it in your profile folder

**Comment by pabloqsr** [comment]
I'm still suffering this issue with v2.17.2 :/
Wasn't it fixed here: https://github.com/docker/compose/issues/9897

**Comment by swingbit** [comment]
hmm, no, it's not solved completely.

I still get unexplained recreates quite often :disappointed:

**Comment by swingbit** [comment]
No, it's not completely solved yet.

I get this quite consistently:

1.  Change a variable in the `.env` file. This changes the configuration, so a recreate is now expected
2. `docker-compose up -d <container>`  # This recreates the container, as expected
3. `docker-compose restart <container>`  # **This recreates the container, again!**

**Comment by swingbit** [comment]
I got it reproducible with a very simple script:

- `docker-compose.yml`:
```
version: '2'

services:

  project:
    env_file: ./project.env
    image: busybox
    entrypoint: "tail -f /dev/null"
```
- `project.env`:
```
X=2
```

1. `docker compose up -d`  # Creates and runs the container
2. `docker compose up -d`  # Nothing done. Good!
3. `docker compose up -d`  # Nothing done. Good!
4. `docker compose up -d`  # Nothing done. Good!
5. `docker compose up -d project` # **Re-creates the container. BAD!**

Notice that I couldn't reproduce this without using `env_file: ./project.env`. Also not reproduced by using the implicit `.env` (thus without `env_file` configuration). 

Versions:
```
$ docker compose version
Docker Compose version v2.17.2

$ docker version
Client: Docker Engine - Community
 Version:           23.0.2
 API version:       1.42
 Go version:        go1.19.7
 Git commit:        569dd73
 Built:             Mon Mar 27 16:19:15 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.2
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.7
  Git commit:       219f21b
  Built:            Mon Mar 27 16:16:26 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.19
  GitCommit:        1e1ea6e986c6c86565bc33d52e34b81b3e2bc71f
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by swingbit** [comment]
Can anyone reproduce the issue with the example I gave above?

**Comment by ndeloof** [comment]
Thanks for sharing a reproduction scenario, I'll look into getting this (eventually) fixed today
