### ISSUE TITLE
[BUG] short and long form includes ignore .env files

### ISSUE THREAD

**Issue by shaunco** [docker/compose#10913]
### Description

The new [include spec](https://github.com/compose-spec/compose-spec/blob/master/14-include.md) says:

Short Syntax:
> Variables are interpolated using values set in the optional .env file in same folder, and is overridden by the local project's environment.

Long Syntax:
> env_file defines an environment file(s) to use to define default values when interpolating variables in the Compose file being parsed. It defaults to .env file in the project_directory for the Compose file being parsed.
...
> The local project's environment has precedence over the values set by the Compose file, so that the local project can override values for customization.

However, docker-compose seems to completely ignore both implicit and explicit `.env` files in includes.

### Steps To Reproduce

1. Create a directory called "postgres" that includes the following files:
   `.env`:
   ```
   POSTGRES_USER=postgres
   POSTGRES_PASSWORD=password
   POSTGRES_PORT=6432
   ```

   `postgres.yml`:
   ```yml
   services:
     postgresql:
       container_name: postgresql
       environment:
         POSTGRES_USER: ${POSTGRES_USER}
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
         PGPORT: ${POSTGRES_PORT}
       image: postgres:14
       ports:
         - ${POSTGRES_PORT}:${POSTGRES_PORT}
   ```
2. Create a directory called "test" (alongside "postgres") with the following file:
   `test.yml`:
   ```yml
   include:
     - ../postgres/postgres.yml
   ```
   OR
   ```yml
   include:
     - path: ../postgres/postgres.yml
       project_directory: ../postgres
       env_file: ../postgres/.env
   ```
3. From a CLI, cd into the `postgres` directory and run: `docker-compose -f .\postgres.yml config` - docker-compose will output valid config with no warnings and the three env variables specified in the `.env` file filled in throughout the config.
4. From a CLI, cd into the `test` directory and run: `docker-compose -f .\test.yml config` - docker-compose will warn that it can't find any of the variables defined in the postgres `.env` file:
```
time="2023-08-18T17:08:08-07:00" level=warning msg="The \"POSTGRES_USER\" variable is not set. Defaulting to a blank string."
time="2023-08-18T17:08:08-07:00" level=warning msg="The \"POSTGRES_PASSWORD\" variable is not set. Defaulting to a blank string."
time="2023-08-18T17:08:08-07:00" level=warning msg="The \"POSTGRES_PORT\" variable is not set. Defaulting to a blank string."
time="2023-08-18T17:08:08-07:00" level=warning msg="The \"POSTGRES_PORT\" variable is not set. Defaulting to a blank string."
time="2023-08-18T17:08:08-07:00" level=warning msg="The \"POSTGRES_PORT\" variable is not set. Defaulting to a blank string."
1 error(s) decoding:

* error decoding 'ports': No port specified: :<empty>
```

### Compose Version

```Text
Docker Compose version v2.20.2-desktop.1
```

**Comment by shaunco** [comment]
@ndeloof - tagging you since you wrote the announcement blog post and might be able to quickly tell me I'm just doing something wrong.

**Comment by shaunco** [comment]
I did a bit more poking around. With 2.20.3 on Ubuntu, both the long and short form let `postgres.yml` find its own `.env` variables while doing `docker-compose -f .\test.yml config` - which didn't work in 2.20.2 on Windows across 2 machines (not sure if it was Windows specific?), but `test.yml` can't reference `${POSTGRES_USER}` (unless it is also specified in `test/.env`) and if I add a `test/.env` file with `POSTGRES_USER=abc` the `postgres` service in the output config still has `postgres` as the username instead of `abc`.

**Comment by pixdad** [comment]
Exactly !
Same issue for me on windows 11 - Docker Compose version v2.20.2-desktop.1

**Comment by ndeloof** [comment]
This is fixed by https://github.com/compose-spec/compose-go/pull/441, included in https://github.com/docker/compose/releases/tag/v2.20.3

**Comment by shaunco** [comment]
@ndeloof - 2.20.3 is still not letting the top-most docker-compose.yml reference .env variables set inside included compose files.

**Comment by ndeloof** [comment]
if `a.yaml` includes `b.yaml` and the latter has a local .env file, this one will be used to parse and resolve b model, but it won't be exposed to `a.yaml` parsing. This is by design. `include` feature is used to let you rely on a set of resources as designed by another team, and let them change their design without much risks for impacts.

**Comment by ndeloof** [comment]
`incmude` let you refer to another compose model, but this is a mechanism to take place _after_ yaml parsing. So variable interpolation takes place as model is parsed, so do yaml anchors and such things, _then_ includes comes into action to add resources from another compose model

**Comment by shaunco** [comment]
Thanks for the explanation! With that being the case, it would seem there is a gap on top-level compose attributes that would allow another `.env` file to be referenced. `--env-file` args can be stacked on the CLI, but that leaves a lot of room for human error. The `env_file` can only be used on a per-service basis, which will create quite a bit of redundancy - but I suppose if we get to 1-2 services per yaml, and that yaml `includes` other yamls, each service can use `env_file` to reference the `.env` files from included yamls to get their vars... Not ideal, but I'll give it a go.

**Comment by shaunco** [comment]
@ndeloof - should I open a new issue for parent `.env` overrides not working in 2.20.3?

**Comment by ndeloof** [comment]
@shaunco fixed in compose-go, thanks

**Comment by shaunco** [comment]
Thank you, @ndeloof! I will give it a shot when a build is available.
