### ISSUE TITLE
labels with list syntax are broken in docker compose v2.23.0

### ISSUE THREAD

**Issue by ghelyar** [docker/compose#11133]
### Description

according to [the compose spec for labels](https://github.com/compose-spec/compose-spec/blob/master/spec.md#labels), there are two syntaxes available - list syntax and dictionary/object/map syntax

in 2.22.0, both of these worked, but in 2.23.0, list syntax does not work.

### Steps To Reproduce

1. Create a `docker-compose.yml` file:
   ```yaml
   services:
     hello_world:
       image: hello-world
       labels:
         - a=b
         - c
   ```
2. on docker compose 2.23.0, run `docker compose config` or `docker compose up`

The error in 2.23.0 is:
```
1 error(s) decoding:

* error decoding 'labels': invalid label ["a=b" "c"]
```

### Compose Version

```Text
Docker Compose version v2.23.0
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    24.0.6
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 19
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc version: v1.1.9-0-gccaecfc
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
```

**Comment by ndeloof** [comment]
This has been fixed by https://github.com/compose-spec/compose-go/pull/475

**Comment by mjgasiorfp** [comment]
Still getting this error:

`* error decoding 'labels': invalid label ["noupstream"]`

When it was defined as:

```
  labels:
    - 'noupstream'
```

Started to work when switched to:

```
  labels:
    - 'noupstream=true'
```

Compose version:

`Docker Compose version v2.23.0-desktop.1`

**Comment by seinshah** [comment]
docker desktop v4.26.1 with docker compose version v2.23.3 also fixes the problem
