### ISSUE TITLE
[BUG] tty not overriding value from extended service

### ISSUE THREAD

**Issue by Daniel-SST** [docker/compose#11135]
### Description

I am trying to use the `extends` functionality to create a reusable component, but it looks like not all values in my main service definition are overriding the values from the extended/referenced definition. Very specifically I am running into the problem that I set `tty: true` in the referenced service, and my main service definition attempts, but fails, to override this with `tty: false`.

The documentation describes the expected behavior as follows:

> #### Merging service definitions
> Two service definitions, the main one in the current Compose file and the referenced one specified by extends, are merged in the following way:
> * [...]
> * Scalars: Keys in the main service definition take precedence over keys in the referenced one.

The documentation does not exclude `tty` anywhere in this section from the expected scalar override behavior.

### Steps To Reproduce

I am running on Ubuntu 22.04 (have not tested other platforms).

The referenced service is located in `common.yaml`:

```yaml
services:
  client-base:
    image: node:20
    working_dir: /app
    tty: true
```

My main service is located in `docker-compose.yaml`:

```yaml
services:
  client-dev:
    extends:
      file: common.yaml
      service: client-base
    container_name: client
    tty: false
```

When running `sudo docker compose config` to see the final configuration I get:

```yaml
name: bug
services:
  client-dev:
    container_name: client
    image: node:20
    networks:
      default: null
    tty: true
    working_dir: /app
networks:
  default:
    name: bug_default
```

You can see here that the `tty` option is still set. This holds true for certain other settings as well, such as `stdin_open`.

### Compose Version

```Text
Docker Compose version v2.21.0
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    24.0.6
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 19
  Running: 3
  Paused: 0
  Stopped: 16
 Images: 479
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc version: v1.1.9-0-gccaecfc
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.2.0-34-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.09GiB
 Name: [REDACTED]
 ID: P6LY:VI3E:T2GQ:RBCJ:PCTU:XXW2:52JK:M6MI:26VH:SN7P:TZEF:QZCQ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  10.42.0.22:32000
  localhost:32000
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

Extends documentation: https://docs.docker.com/compose/compose-file/05-services/#extends
Merge & override documentation: https://docs.docker.com/compose/compose-file/13-merge/

It'd be great if the usage of the `!reset` YAML tag in the `extends` scenario could be described as well in de docs. I am unsure now if this should work or not. From testing it, I don't believe it works.

**Comment by ndeloof** [comment]
The root cause is that `tty: false` is set to a go boolean in compose-go and - as default value - will be ignored during merge.
This should be addressed by compose-go/v2 but in the meantime you can rely on `!reset` to remove the extended service value:
```yaml
services:
  client-dev:
    extends:
      file: common.yaml
      service: client-base
    container_name: client
    tty: !reset false  # this will remove `tty` config from extended service definition
```

**Comment by Daniel-SST** [comment]
Thanks for the suggestion, but I'm afraid it does not appear to work:

```yaml
services:
  client-dev:
    extends:
      file: common.yaml
      service: client-base
    container_name: client
    tty: !reset false
```
Then running `sudo docker compose config` gives me:

```yaml
name: bug
services:
  client-dev:
    container_name: client
    image: node:20
    networks:
      default: null
    tty: true
    working_dir: /app
networks:
  default:
    name: bug_default
```

This still shows `tty: true`... Assuming that this is the config that will be acted upon by docker, that won't solve the issue.

**Comment by ndeloof** [comment]
tried to reproduce, but works for me:
```
$ cat compose.yaml 
services:
  client-dev:
    extends:
      file: common.yaml
      service: client-base
    container_name: client
    tty: !reset false
$ cat common.yaml 
services:
  client-base:
    image: node:20
    working_dir: /app
    tty: true
 $ docker compose config
name: truc
services:
  client-dev:
    container_name: client
    image: node:20
    networks:
      default: null
    working_dir: /app
...
```

Can you please try using latest docker-compose ? (just download binary from releases page and install under ~/.docker/cli-plugins)

**Comment by Daniel-SST** [comment]
> Can you please try using latest docker-compose ? (just download binary from releases page and install under ~/.docker/cli-plugins)

Thanks, that did the trick! I needed to add it to `/usr/libexec/docker/cli-plugins`, as that home folder location was not picked up. Here's to hoping this will make it to the Ubuntu packages asap! 😄
