### ISSUE TITLE
[BUG] compose config ignores the service to show the config for when given as argument

### ISSUE THREAD

**Issue by luciangabor** [docker/compose#11608]
```console

$ docker compose -f - config service1 <<-'EOF'
name: select-service
services:
  service1:
    image: service1
  service2:
    image: service2
EOF
name: select-service
networks:
  default:
    name: select-service_default
services:
  service1:
    image: service1
    networks:
      default: null
  service2:
    image: service2
    networks:
      default: null

```

https://github.com/docker/compose/issues/11587#issuecomment-1991779214

**Comment by ndeloof** [comment]
fixed by https://github.com/docker/compose/pull/11604

**Comment by luciangabor** [comment]
This is not really fixed - it works if services don't have profiles but when profiles are involved the behavior is strange:

```console

# with my own build of what's now in main
$ docker-compose-linux-x86_64 version
Docker Compose version 5a1ba0e

# and this compose.yaml
$ cat compose.yaml 
services:
  s1:
    profiles:
      - p1
    image: image

  s2:
    profiles:
      - p2
    image: image

# this shouldn't "work"
$ docker-compose-linux-x86_64 config s1
name: config
services:
  s1:
    profiles:
      - p1
    image: image
    networks:
      default: null
networks:
  default:
    name: config_default

# this definitely shouldn't work
$ docker-compose-linux-x86_64 --profile p2 config s1
name: config
services:
  s1:
    profiles:
      - p1
    image: image
    networks:
      default: null
networks:
  default:
    name: config_default

# this doesn't work, but it should
$ docker-compose-linux-x86_64 --profile '*' config s1
no such service: s1

```

**Comment by ndeloof** [comment]
Compose commands, when ran with an explicit service name, automagically enable the target service even it's not active by profile.
You last example definitely demonstrates a bug

**Comment by luciangabor** [comment]
oh uau, that's actually true - this thing is definitely a sea creature - nothing is plane/plain :D (is the name of the mascot chosen?)
