### ISSUE TITLE
[BUG] Sometimes Docker Compose does not attach corresponding networks to containers

### ISSUE THREAD

**Issue by alexandrubau** [docker/compose#11709]
### Description

I have a `docker-compose.yml` file which defines multiple services. All services are part of a network called `default`. Some of them are also part of an external network called `proxy`.

Upon running `docker compose up` there is a chance that some of the services do not have all their specified networks attached (it's either `proxy` or `default` missing). There is also the possibility of everything working accordingly. I've come to this conclusion by inspecting individual services multiple times using `docker inspect` command. 

Running `docker compose down` followed by `docker compose up` several times solves this issue for me.

I've tried searching for some information in [dockerd and containerd logs](https://docs.docker.com/config/daemon/logs/) but I couldn't find anything useful.

### Steps To Reproduce

Running `docker compose up` with the following `docker-compose.yml` file displays the issues listed above.

<details>
  <summary>docker-compose.yml</summary>

```yaml
services:

  node:
    build:
      context: ../
      dockerfile: .docker/node/Dockerfile
      target: local
    volumes:
      - ../:/var/www/html
    environment:
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
    command: ["npm", "run", "start:debug"]
    networks:
      - default
      - proxy
    ports:
      - "${NODE_DEBUG_LOCAL_PORT}:9229"
    depends_on:
      - postgres

  langfuse:
    image: ghcr.io/langfuse/langfuse:2
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres?schema=langfuse
      HOSTNAME: 0.0.0.0
      PORT: 80
      NEXTAUTH_URL: https://lf-${APP_HOSTNAME}
      NEXTAUTH_SECRET: ${LANGFUSE_SECRET}
      SALT: ${LANGFUSE_SALT}
    networks:
      - default
      - proxy
    depends_on:
      - postgres
    restart: on-failure:3

  postgres:
    image: citusdata/citus:12.1-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - default
    restart: on-failure:3

  pgadmin:
    image: dpage/pgadmin4:8.4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - pg:/var/lib/pgadmin
    networks:
      - default
      - proxy
    depends_on:
      - postgres
    restart: on-failure:3

volumes:
  db: {}
  pg: {}

networks:
  proxy:
    external: true
  default:
    external: false


```
</details>

### Compose Version

```Text
Docker Compose version v2.24.6-desktop.1
```

### Docker Environment

<details>
  <summary>Command Output</summary>

```Text
Client:
 Version:    25.0.3
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1-desktop.4
    Path:     /Users/admin/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.6-desktop.1
    Path:     /Users/admin/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.24
    Path:     /Users/admin/.docker/cli-plugins/docker-debug
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/admin/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.22
    Path:     /Users/admin/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     /Users/admin/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.0.1
    Path:     /Users/admin/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/admin/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.5.0
    Path:     /Users/admin/.docker/cli-plugins/docker-scout
WARNING: Plugin "/Users/admin/.docker/cli-plugins/docker-scan" is not valid: failed to fetch metadata: fork/exec /Users/admin/.docker/cli-plugins/docker-scan: no such file or directory

Server:
 Containers: 5
  Running: 5
  Paused: 0
  Stopped: 0
 Images: 13
 Server Version: 25.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.6.16-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 8
 Total Memory: 7.658GiB
 Name: docker-desktop
 ID: 61614803-589f-4bad-9a49-76ace07bab78
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profil
```
</details>

### Anything else?

Running Docker Desktop on MacOS Sonoma 14.4.1 (23E224)

**Comment by glours** [comment]
Hello @alexandrubau 
This is a known issue which have been fixed in [Compose v2.24.7](https://github.com/docker/compose/releases/tag/v2.24.7), can you update to the latest version please.
I'll close the issue, let me know if you can reproduce it and I'll re-open it.

**Comment by alexandrubau** [comment]
Updated to latest version and everything works. Thank you @glours !

**Comment by gaby** [comment]
@glours This still happens, in my case both networks are external. It must be a race condition cause sometimes the container gets both networks and sometimes it gets one.
