### ISSUE TITLE
[BUG] `docker-compose up` duplicating logs after upgrading

### ISSUE THREAD

**Issue by Kangaroux** [docker/compose#13144]
### Description

After a minor version upgrade (2.38.2 -> 2.39.1) container logs are being duplicated

### Steps To Reproduce

https://github.com/jessienyan/booruview

1. Using 2.38.2, run `docker compose up --build` (or `./dev.sh`)
2. Observe container logs are normal
3. Using 2.39.1, run `docker compose up --build` (or `./dev.sh`)
4. Observe container logs are duplicated

`docker compose logs -f <container>` has the correct output

`up`
```
client-1  | transforming...
client-1  | transforming...
client-1  | ✓ 158 modules transformed.
client-1  | ✓ 158 modules transformed.
client-1  | rendering chunks...
client-1  | rendering chunks...
client-1  | computing gzip size...
client-1  | computing gzip size...
client-1  | dist/index.html                               1.98 kB │ gzip:  0.88 kB
client-1  | dist/assets/bootstrap-icons-pHno5dML.woff2  130.48 kB
client-1  | dist/assets/bootstrap-icons-DIW_sQAl.woff   176.18 kB
client-1  | dist/assets/index-DtRUWQEb.css               96.94 kB │ gzip: 17.57 kB
client-1  | dist/assets/index-CjOb5qaj.js               195.58 kB │ gzip: 67.92 kB │ map: 906.22 kB
client-1  | dist/index.html                               1.98 kB │ gzip:  0.88 kB
client-1  | dist/assets/bootstrap-icons-pHno5dML.woff2  130.48 kB
client-1  | dist/assets/bootstrap-icons-DIW_sQAl.woff   176.18 kB
client-1  | dist/assets/index-DtRUWQEb.css               96.94 kB │ gzip: 17.57 kB
client-1  | dist/assets/index-CjOb5qaj.js               195.58 kB │ gzip: 67.92 kB │ map: 906.22 kB
client-1  | built in 1624ms.
client-1  | built in 1624ms.
```

`logs -f client`
```
client-1  | transforming...
client-1  | ✓ 158 modules transformed.
client-1  | rendering chunks...
client-1  | computing gzip size...
client-1  | dist/index.html                               1.98 kB │ gzip:  0.88 kB
client-1  | dist/assets/bootstrap-icons-pHno5dML.woff2  130.48 kB
client-1  | dist/assets/bootstrap-icons-DIW_sQAl.woff   176.18 kB
client-1  | dist/assets/index-DtRUWQEb.css               96.94 kB │ gzip: 17.57 kB
client-1  | dist/assets/index-CjOb5qaj.js               195.58 kB │ gzip: 67.92 kB │ map: 906.22 kB
client-1  | built in 1624ms.
```

### Compose Version

```Text
Docker Compose version v2.39.1
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    28.3.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.26.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.39.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 5
  Running: 1
  Paused: 0
  Stopped: 4
 Images: 271
 Server Version: 28.3.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 CDI spec directories:
  /etc/cdi
  /var/run/cdi
 Discovered Devices:
  cdi: amd.com/gpu=0
  cdi: amd.com/gpu=all
 Swarm: inactive
 Runtimes: amd io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05044ec0a9a75232cad458027ca83437aae3f4da
 runc version: v1.2.5-0-g59923ef
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.12.10-76061203-generic
 Operating System: Pop!_OS 22.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 31.25GiB
 Name: desktop
 ID: 3dfbff84-5b48-4581-ba77-b324887ff02f
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 37
  Goroutines: 58
  System Time: 2025-08-10T12:59:16.803040294-04:00
  EventsListeners: 0
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

```bash
$ less /var/log/dpkg.log | grep docker | grep upgrade
2025-08-07 20:48:20 upgrade docker-ce-cli:amd64 5:28.3.2-1~debian.12~bookworm 5:28.3.3-1~debian.12~bookworm
2025-08-07 20:48:21 upgrade docker-ce:amd64 5:28.3.2-1~debian.12~bookworm 5:28.3.3-1~debian.12~bookworm
2025-08-07 20:48:24 upgrade docker-buildx-plugin:amd64 0.25.0-1~debian.12~bookworm 0.26.1-1~debian.12~bookworm
2025-08-07 20:48:25 upgrade docker-ce-rootless-extras:amd64 5:28.3.2-1~debian.12~bookworm 5:28.3.3-1~debian.12~bookworm
2025-08-07 20:48:25 upgrade docker-compose-plugin:amd64 2.38.2-1~debian.12~bookworm 2.39.1-1~debian.12~bookworm
```

**Comment by glours** [comment]
Hey @Kangaroux 
Compose `v2.39.2` has been released last Friday with a fix for this issue, can you try it?

**Comment by Newspaperman57** [comment]
Hi @glours 
I can see the `v2.39.2` in the releases-tab, but apparently it's not in the apt repository yet (at least for ubuntu 24.04), is this on purpose? 
This bug is disruptive to me and i would like it fixed, but as far as i can see my only option is to manually install the latest version? Changing the source from `stable` to `test` also only offers `2.39.1`

Thank you in advance
```
mathias@FLPC8286:~$ sudo apt update
Hit:1 http://security.ubuntu.com/ubuntu noble-security InRelease
Hit:2 https://download.docker.com/linux/ubuntu noble InRelease                                                                                                                                                                    
[...]
mathias@FLPC8286:~$ sudo apt upgrade docker-compose-plugin
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
docker-compose-plugin is already the newest version (2.39.1-1~ubuntu.24.04~noble).
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by coredumperror** [comment]
I am also seeing this bug in MacOS with the latest version of Docker Desktop (4.44.2). Docker compose version is v2.39.1-desktop.1.

Downgrading to Docker Desktop 4.43.2 (199162) (with Compose: v2.38.2-desktop.1) fixed the issue. 

It also fixed an odd problem I started getting when Docker Desktop updated itself today, where pressing Ctrl-C on an active `docker compose up --watch` instance would _immediately_ kill it and return me to the command line, and _not_ stop any of the containers. On version 4.43.2, Ctrl-C works as expected, triggering the shutdown process and eventually stopping each container before returning me to the command line.

Possibly related to the duplicated logs?

**Comment by czyzby** [comment]
Also experiencing the bug. Can confirm that `docker logs` of the containers are not actually duplicated though.

**Comment by dpk-it** [comment]
the same issue (WSL, Docker Desktop 4.44.3)

```
$ docker compose version
Docker Compose version v2.39.1-desktop.1
```

**Comment by rasputyashka** [comment]
apparently this is fixed in 2.39.2

**Comment by coredumperror** [comment]
As a heads up, Docker Desktop 4.44.3 (the latest release) does not include that version of Docker Compose. It's still got 2.39.1-desktop.1.

**Comment by Dev-Mohamed-Ali** [comment]
the issue in compose itself and still not fixed yet , if you `docker build`  it works fine

**Comment by ndeloof** [comment]
> As a heads up, Docker Desktop 4.44.3 (the latest release) does not include that version of Docker Compose. It's still got 2.39.1-desktop.1.

You can download Compose binaries from https://github.com/docker/compose/releases/tag/v2.39.2
install as `$HOME/.docker/cli-plugin/docker-compose[.exe]`

**Comment by coredumperror** [comment]
Thanks! 

Though heads up for MacOS users: Apple's overbearing security stance makes it impossible to use that binary. You'll get an error from MacOS that looks like this: 

<img width="275" height="257" alt="Image" src="https://github.com/user-attachments/assets/697c6e33-484d-4963-aa13-f25e268f20fb" />

Guess we'll just have to wait for a new Docker Desktop version that incorporates the new docker-compose.

**Comment by dexterbt1** [comment]
I am using Docker Desktop on macOS / Apple Silicon and I can't wait for the official release, so I manually replaced the older version with the  updated v2.39.2 release.

Make sure you have the "Full Disk Access" enabled to your terminal.

<img width="863" height="255" alt="Image" src="https://github.com/user-attachments/assets/583d80c1-6302-46bb-a4ff-7b7a425b3ea0" />

**Comment by sebastianpikand** [comment]
running this on my mac helped me fix it (helped me upgrade the minor version):

```
mkdir -p ~/.docker/cli-plugins
curl -SL https://github.com/docker/compose/releases/download/v2.38.2/docker-compose-darwin-aarch64 -o ~/.docker/cli-plugins/docker-compose
chmod +x ~/.docker/cli-plugins/docker-compose
export DOCKER_CLI_PLUGIN_EXTRA_DIRS="$HOME/.docker/cli-plugins"
docker compose version
```

**Comment by ErwanGit** [comment]
This seems to be resolved on my end with Docker Desktop v4.45.0 / Docker Compose v2.39.2-desktop.1 on macOS

**Comment by coredumperror** [comment]
Yeah, same here. Docker Desktop for Mac wouldn't offer an update to 4.45.0 in-app to me, but I downloaded the installer from the Docker website and it's working great.

**Comment by goldmont** [comment]
Hi,

Why is it not available yet on the docker PPA? [v2.39.2](https://github.com/docker/compose/releases/tag/v2.39.2) relased a month ago.

**Comment by phproberto** [comment]
I also had this issue on macos:

```
$ docker compose version
Docker Compose version v2.39.1-desktop.1
```

I went to docker desktop page and just downloaded the available version:

https://www.docker.com/products/docker-desktop/

I reinstalled it replacing the current one and the issue is fixed:

```
$ docker compose version
Docker Compose version v5.0.1
```
