### ISSUE TITLE
Compose doesn't collaborate with Swarm when 1 service has 2 dependencies

### ISSUE THREAD

**Issue by jpetazzo** [docker/compose#1528]
## What I do

`docker-compose up` with the following `docker-compose.yml` file, against a 4-nodes Swarm cluster:

```yaml
hasher:
  image: jpetazzo/dockercoins_hasher:1433781053
  ports: ['8002:80']
redis: {image: redis}
rng:
  image: jpetazzo/dockercoins_rng:1433781053
  ports: ['8001:80']
webui:
  image: jpetazzo/dockercoins_webui:1433781053
  links: [redis]
  ports: ['8000:80']
  volumes: ['webui/files/:/files/']
worker:
  image: jpetazzo/dockercoins_worker:1433781053
  links: [rng, hasher, redis]
```

## What I expect

The app comes up (with all containers on the same node, since `redis`, `rng`, and `hasher` are all dependencies of `worker`).

## What I see

Swarm places `redis`, `rng`, and `hasher` on random nodes. If at least two containers end up on different nodes,  I get the following error:

```
Unable to find a node fulfilling all dependencies: --link=dockercoins_hasher_1:dockercoins_hasher_1 --link=dockercoins_hasher_1:hasher --link=dockercoins_hasher_1:hasher_1 --link=dockercoins_redis_1:dockercoins_redis_1 --link=dockercoins_redis_1:redis --link=dockercoins_redis_1:redis_1 --link=dockercoins_rng_1:dockercoins_rng_1 --link=dockercoins_rng_1:rng --link=dockercoins_rng_1:rng_1
```

## Possible resolutions

- run a full dependency resolution and submit appropriate placement constraints to Swarm
- say that it's Not Our Problem, By Design©

**Comment by aanand** [comment]
Swarm is supposed to co-schedule linked containers. I've not confirmed that it was still doing so since 0.2.0, though - what version are you using?

**Comment by timfallmk** [comment]
@aanand @jpetazzo I can confirm that scheduling seems to properly schedule linked containers on 0.2.0+

**Comment by jpetazzo** [comment]
Have you tried when there are 2 dependencies?

I don't understand how that could work without Swarm passing and explicit
placement constraint.

**Comment by aanand** [comment]
Right, I see the issue. If C depends on both A and B, but A and B are independent, Swarm won't know that it needs to co-schedule all three.

I think this should be solved in the long term by adding a "multi-create" command to the Docker API, so that Swarm can take all scheduling constraints into consideration (ping @shykes and @vieux, with whom I vaguely recall discussing this before).

Short-term, perhaps we should recommend that people set an affinity constraint. It can be done based on Compose's labels, e.g.

```yaml
a:
  image: me/a

b:
  image: me/b
  environment:
    - "affinity:com.docker.compose.service==a"

c:
  image: me/c
  links:
    - a
    - b
  environment:
    - "affinity:com.docker.compose.service==a"
```

Except there's no guarantee that `a` will be spun up before `b`. Hmmmm.

**Comment by jpetazzo** [comment]
Brain dump:
- one possibility is to totally dodge the issue and say "overlay network will take care of this," but it means that this won't work until we ship an overlay network that works out of the box
- another possibility is to have Compose compute the entire dependency tree (which I believe it does anyway) then co-schedule all containers explicitly
- yet another possibility is to make Compose extensible so that links will execute a custom Docker command (which can setup an ambassador, overlay network, or whatever)

The least intrusive solution would be the 2nd one, it seems, but if resource constraints are also specified, then we need group scheduling (as discussed a while ago after my presentations in Montréal) — IOW, the ability to create not 1 container at a time, but a group; allowing Swarm to aggregate all resource requirements when picking the target host.

Let me know if I can do anything to help, as I think this will be a pretty useful improvement.

Thanks for looking into this!

**Comment by dnephin** [comment]
Revisiting this issue.

We're about to ship the overlay network which solves the issue for `links` and `net`, but it doesn't solve the problem for `volumes_from`.

So that leaves us with one possible solution on the compose side:
*  calculate the whole graph , and add affinities to every container for every other container in the graph when `volumes_from` is used

and one possible solution on the swarm side:
* support some form of container "group" (aka "multi-create" from https://github.com/docker/compose/issues/1528#issuecomment-110787037)) which would require a new API

I think it's probably easier (and less intrusive) to handle this on the compose side (at least for now).

**Comment by jpetazzo** [comment]
FYI—I did some very extensive work with ECS and Swarm recently, to deploy non-trivial applications; and I found that having the concept of a group of containers (whether you call it "pod" or anything else) was extremely powerful. To put things differently: when scaling my app, I ended up deploying groups of containers anyway, and bewailing the lack of proper groups in Compose/Swarm ;-)

**Comment by csaintc** [comment]
:+1:

**Comment by dnephin** [comment]
Now that we're changing to user defined network which support multi-host, I don't think this is an issue anymore, is that right?

**Comment by jpetazzo** [comment]
I agree, I think we can close this, and let overlay networking do its magic!
