### ISSUE TITLE
Compose 1.4.0rc2 is referencing misnamed/nonexisting images

### ISSUE THREAD

**Issue by toli** [docker/compose#1797]
I am running into an issue with docker-compose RC2 where it's referencing Docker images that don't exist.
it seems that it's trying to reference a name that doesn't exist, and is not in the usual `compose_module_1` variety. 
Seems to be referencing `some-sha_compose_module_1` instead:
```
docker-compose up -d
Recreating 5cd1ee5720_5cd1ee5720_5cd1ee5720_5cd1ee5720_5cd1ee5720_5cd1ee5720_5cd1ee5720_5cd1ee5720_compose_reghubdb_1...
No such image: 5370e5230ea776103dbd683e2fc4a51387860607e5f44024c5a10b2a8deb7094
```
Version check:
```
> docker-compose version
docker-compose version: 1.4.0rc2
docker-py version: 1.3.1
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1j 15 Oct 2014
```
This is reproducible, has happened multiple times when i blow all the containers/images away and try again.

/cc @aanand

**Comment by dnephin** [comment]
I think there are a few things going on here:

1. Something is preventing the original container from being cleanly removed when we go to recreate the container. We've been seeing this a bunch, but don't have a good understanding of what is causing it.
2. To work around (1) we added a "remove duplicate container", but it seems to be removing the wrong container. It's removing the new one instead of the original
3. The image used by the original is now gone. I guess you removed it? I think if the first two issues are fixed this won't be a problem anymore. I'm not sure how smart-recreate is supposed to handle this case. If it's supposed to build the image, or just give a better error about it being missing.

**Comment by dnephin** [comment]
@toli are you able to reproduce this with 1.5.0? 

If you remove all the containers it really shouldn't be recreating from an existing container.

**Comment by Ramshackle-Jamathon** [comment]
Commands for removing all docker containers:
docker stop $(docker ps -a -q)
docker rm $(docker ps -a -q)

**Comment by dnephin** [comment]
I believe we fixed this in one of the 1.5.x releases.

**Comment by chrisgahlert** [comment]
I can confirm that this is still happening in the current version:
* docker-compose version 1.8.1, build 878cff1
* Docker version 1.12.1, build 23cf638

In my case I have multiple compose files (inheriting from each other via `docker-compose -p child1 -f parent.yml -f child1.yml`) running the same/similar containers on the same host. 

When running a `docker-compose pull` and `docker-compose up --build -d` it seems that sometimes the error described above occurs.

**Comment by afalko** [comment]
We are seeing this with 1.7.1. We wind up having to reboot machines afflicted by this to resolve. The docker daemon says that it stopped container, but it doesn't actually do it. If we restart the docker daemon, then docker-compose is able to work, but not for containers that have the same port.
