### ISSUE TITLE
Hostname lost after rebuilding linked container

### ISSUE THREAD

**Issue by mikehaertl** [docker/compose#2174]
Say I have 2 containers, one is linked to the other:

```
foo:
    image: php:5.6.10-apache
    links:
        - bar
bar:
    image: php:5.6.10-apache
```

I can now start the containers, check for the container ID of `foo` and ping `bar` from `foo`:

```
$ docker-compose up -d
Creating dct_bar_1...
Creating dct_foo_1...

$ docker ps
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS               NAMES
6ddb60dd97dd        php:5.6.10-apache   "apache2-foreground"   59 seconds ago      Up 1 seconds        80/tcp              dct_foo_1
809a937f3913        php:5.6.10-apache   "apache2-foreground"   59 seconds ago      Up 1 seconds        80/tcp              dct_bar_1

$ docker exec -ti 6ddb6 ping bar
PING bar (172.17.0.44): 56 data bytes
64 bytes from 172.17.0.44: icmp_seq=0 ttl=64 time=0.061 ms
64 bytes from 172.17.0.44: icmp_seq=1 ttl=64 time=0.059 ms
```

Now if i stop the containers, remove `bar` and run the containers again, the hostname of `bar` is no longer available in `foo`. I first have to also rebuild `foo`:

```
$ docker-compose stop
Stopping dct_foo_1... done
Stopping dct_bar_1... done

$ docker-compose rm bar
Going to remove dct_bar_1
Are you sure? [yN] y
Removing dct_bar_1... done

$ docker-compose up -d
Creating dct_bar_1...
Starting dct_foo_1...

$ docker exec -ti 6ddb6 ping bar
ping: unknown host
```

This is quite inconvenient as it means, I can not recreate any linked container without also recreating all containers where the removed one is linked to.

```
$ docker-compose --version
docker-compose version: 1.4.0
$ docker --version
Docker version 1.8.2, build 0a8c2e3
```

**Comment by dnephin** [comment]
Sorry about this. We fixed this bug in `1.4.1` and `1.4.2`. If you upgrade it should be fixed.

**Comment by mikehaertl** [comment]
@dnephin I've upgraded to 1.5.0 and the problem is still there.

**Comment by dnephin** [comment]
Ok, I think I assumed this was a different bug, but I think I see what's happening here.

Dependents are only recreated if their dependencies get the action 'recreate', but in this case it's getting the action 'create' (since it was removed), which isn't triggering the create of the dependent.

**Comment by mikehaertl** [comment]
@dnephin I confirm that the issue seems to be gone in 1.5.1. Thanks!
