### ISSUE TITLE
/etc/hosts sometimes corrupted with restart=always at docker daemon restart

### ISSUE THREAD

**Issue by approxit** [docker/compose#2454]
### Versions:

```
# docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

# docker-compose version
docker-compose version: 1.5.1  
docker-py version: 1.5.0  
CPython version: 2.7.6  
OpenSSL version: OpenSSL 1.0.1f 6 Jan 2014

# uname -a
Linux docker-test 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```
### Case:

I have compose with my app and mysql running in container outside of that compose. Mysql container have restart=always too.

```
# docker-compose.yml
web:
  image: some_project_image
  restart: always
  links:
    - rabbitmq
  external_links:
    - mysql:db

nginx:
  image: nginx
  restart: always
  links:
    - web

worker:
  image: some_project_image
  restart: always
  links:
    - rabbitmq
  external_links:
    - mysql:db

beat:
  image: some_project_image
  restart: always
  links:
    - rabbitmq
  external_links:
    - mysql:db

rabbitmq:
  image: rabbitmq
  restart: always
```
### Expectations:

Every container knows IP's of linked containers by docker magic. Using restart=always policy ensures that docker will take care of for eg. system reboot with auto starting things we want.
### Problem:

Sometimes containers (worker and beat) fails to start. Reason: `Unknown MySQL server host 'db'` (it's `unknown` not `can't connect`. I'm aware of longer startup times, but that's not the case). It's a little 'play with it until it breaks' to catch it. My score is somewhere around 10%~20% of tries..
### Analysis:

Everything looks like #2445 but much more different situation. Starting order / containers IP looks not so important: MySQL can receive lower or higher IP than problematic containers. Below we have example of situation when problem occurs:

```
# docker inspect --format '{{ .NetworkSettings.IPAddress }} - {{ .Name }}' $(docker ps -q)
172.17.0.6 - /project_beat_1
172.17.0.4 - /project_nginx_1
172.17.0.2 - /project_web_1
172.17.0.5 - /project_worker_1
172.17.0.7 - /project_rabbitmq_1
172.17.0.3 - /mysql

# docker cp project_beat_1:/etc/hosts hosts && cat hosts (because container is still restarting in background)
172.17.0.6      9622f7ff5749
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
        db f976697bfb2c mysql
        project_rabbitmq_1 caea9351f869
        rabbitmq caea9351f869 project_rabbitmq_1
        rabbitmq_1 caea9351f869 project_rabbitmq_1
```

Or another situation:

```
# docker cp project_beat_1:/etc/hosts hosts && cat hosts (because container is still restarting in background)
172.17.0.3      9622f7ff5749
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
        db f976697bfb2c mysql
172.17.0.7      project_rabbitmq_1 caea9351f869
172.17.0.7      rabbitmq caea9351f869 project_rabbitmq_1
172.17.0.7      rabbitmq_1 caea9351f869 project_rabbitmq_1
```

Pay attention to empty IP column in 1st example and 2nd. Policy restart=always is restarting container with corrupted /etc/hosts and fails forever until we manually run `docker restart project_beat_1` to refresh them. In `/var/log/upstart/docker.log` we can see nothing but 'everything is alright here'.
### Ideas?

Upon `/etc/hosts` render time container IP have a unhandled gap when is not yet accessible, because everything is happening in parallel?

**Comment by dnephin** [comment]
I'm guessing the reason that `restart=always` isn't fixing the problem is because it's re-using the same container, and docker itself doesn't  realize the container needs to be updated, so it doesn't re-write the `/etc/hosts` when it starts the container.

@mavenugo This sounds related to libnetworking. Have you see this before? Is there an issue open for it already?

**Comment by approxit** [comment]
Of course that it's using same container. There's no doubt. Docker itself may not notice that, or see no difference in container prefs and docker host so update is not needed. How about forcing `etc/hosts` reload?

To check this I reproduced the case once again (2nd try...) and manually restarted mysql, then checked `/etc/hosts`. Entry for mysql was updated with correct IP, but 3 entries for project_rabbitmq_1 was untouched and still corrupted with missing IPs. `restart=always` could reload `etc/hosts` every time... but still, it would be masking the core problem. By the way Docker brainacks probably have good reasons to not reload `etc/hosts` every `restart=always`.

**Comment by dnephin** [comment]
Docker 1.10 no longer uses `/etc/hosts` and instead uses a DNS server, so it's very likely this is resolved.

Please try with Docker 1.10 and let us know if it's fixed.

**Comment by jmkgreen** [comment]
@dnephin only with user-defined networks. Without this and with `link` you still get `/etc/hosts` entries.

**Comment by mavenugo** [comment]
@approxit  If am not wrong, we had a few issues with links and `--restart` policy. @cpuguy83 will have more information and he worked on resolving a few of them in 1.10.

Re :
> only with user-defined networks. Without this and with link you still get /etc/hosts entries.

@jmkgreen  thats correct. Compose v2 uses `user-defined networks` by default. You can run your external service in the same user-defined network and it should work with DNS.

**Comment by cpuguy83** [comment]
I'm really not sure I follow the conversation here.
Linked container entries do get updated when the IP changes (ie, when the linked containers restart). A container can't start if any of it's linked containers are down.

With the `-x-networking` stuff, I'm not sure how links behave (and is different now that this is all changed in compose stable, I'm sure), but links do not create hard-depdencies between containers on user-defined networks... so conceivably a container can come up that has a link, but the link is not up, and as such has no DNS entry.

**Comment by ijc** [comment]
Issue grooming: closing as stale. If this still happens with the latest versions of everything please reopen or file a fresh issue.
