### ISSUE TITLE
Service instance not aware of its own generated hostname

### ISSUE THREAD

**Issue by brunoborges** [docker/compose#2551]
To demonstrate the problem, here's a test case scenario. Given the following fictitious **~/sample/docker-compose.yml**:

        master:
          build: master/
          hostname: master
        slave:
          build: slave/

Docker Compose is called to bring these services up:

        $ docker-compose up -d

A process inside **master** can ping itself through the hostname **master**. Such command works:

        $ docker exec -ti <master id> ping master

A process inside **master** can also ping the **slave** service with the generated hostname **sample_slave_0**:

        $ docker exec -ti <master id> ping sample_slave_0

A process inside **slave** will **not** be able to ping itself with the generated hostname:

        $ docker exec -ti <slave id> ping sample_slave_0

Now given the problem statement above, a possible solution would be to include **hostname: slave** in the definition of the **slave** service. The problem is that **slave** is a scalable service and therefore cannot have a statically defined hostname. It is also important that the process running inside **slave** knows about its own hostname so it can communicate with **master** to self-register in whatever process is inside of **master**.

Is there any work in progress to support such scenario?

**Comment by dnephin** [comment]
Is this a duplicate of #2525 ?

It's unlikely this will change for links, since they are already deprecated and being replaced by user defined networks. There is an ongoing discussion about how user defined networks should alias the containers (#2312, docker/libnetwork#737).

**Comment by dnephin** [comment]
@mavenugo do you think this will work as described with the proposed `--hostname-alias` ?

**Comment by cesarhernandezgt** [comment]
@dnephin , if links are already deprecated, the documentation should be uptaded because I didn't find any deprecation warning in the official documentation of docker-compose. https://docs.docker.com/compose/compose-file/#links

**Comment by dnephin** [comment]
I guess it's not official until we actually have a proper replacement. It will be documented in the next release.

**Comment by jippi** [comment]
:+1:

**Comment by rafabene** [comment]
I was able to solve it through these instructions: https://gist.github.com/rafabene/79b0bc0a8b4e8ee2a9d5

**Comment by brunoborges** [comment]
@rafabene your test does not run exactly the use case described here. I commented on your repo the problem with your test case.

**Comment by brunoborges** [comment]
@dnephin @jippi can't this issue be fixed without depending on libnetwork aliases?

**Comment by dnephin** [comment]
No, it depends on changes to the engine (which uses libnetwork).

It looks like this is fixed in Compose 1.6-rc2 using Docker 1.10-rc2 (using compose format v2). When a user defined network is used, a container can ping itself using the service name (which is added as an alias).

**Comment by dnephin** [comment]
Since this is fixed in 1.6 (using compose file format v2, https://github.com/docker/compose/blob/master/docs/compose-file.md#version-2) I'm going to close this issue.

If you're able to reproduce it with that version, please re-open or leave a comment.

**Comment by brunoborges** [comment]
@dnephin I tried Docker 1.10 and Compose 1.6 and this still happens. Can you please reopen this bug?

**Comment by brunoborges** [comment]
This issue is still reproducible with the following use case.

```
bruno@lenovo: compose-net$ cat docker-compose.yml 
version: '2'
services:
  slave:
    image: busybox
    command: top
    networks:
      - mynet
    depends_on:
      - master 
  master:
    image: busybox 
    command: top
    container_name: master 
    hostname: master
    networks:
      - mynet
networks:
  mynet:
    driver: bridge
```

Then I execute the Compose above as daemon:

```
bruno@lenovo: compose-net$ docker-compose up -d
```

This is the state of these containers:

```
bruno@lenovo: compose-net$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
0f734f3eca10        busybox             "top"               2 seconds ago       Up 2 seconds                            composenet_slave_1
9c8c035f9290        busybox             "top"               3 seconds ago       Up 2 seconds                            master
```

And these are the tests:

```
bruno@lenovo: compose-net$ docker exec -ti 9c8c035f9290 ping -c 1 master
PING master (172.20.0.2): 56 data bytes
64 bytes from 172.20.0.2: seq=0 ttl=64 time=0.052 ms

--- master ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.052/0.052/0.052 ms

bruno@lenovo: compose-net$ docker exec -ti 9c8c035f9290 ping -c 1 composenet_slave_1
PING composenet_slave_1 (172.20.0.3): 56 data bytes
64 bytes from 172.20.0.3: seq=0 ttl=64 time=0.066 ms

--- composenet_slave_1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.066/0.066/0.066 ms

bruno@lenovo: compose-net$ docker exec -ti 9c8c035f9290 ping -c 1 0f734f3eca10
ping: bad address '0f734f3eca10'

bruno@lenovo: compose-net$ docker exec -ti 9c8c035f9290 ping -c 1 9c8c035f9290
ping: bad address '9c8c035f9290'
bruno@lenovo: compose-net$ docker exec -ti 0f734f3eca10 ping -c 1 master
PING master (172.20.0.2): 56 data bytes
64 bytes from 172.20.0.2: seq=0 ttl=64 time=0.049 ms

--- master ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.049/0.049/0.049 ms

bruno@lenovo: compose-net$ docker exec -ti 0f734f3eca10 ping -c 1 composenet_slave_1
PING composenet_slave_1 (172.20.0.3): 56 data bytes
64 bytes from 172.20.0.3: seq=0 ttl=64 time=0.021 ms

--- composenet_slave_1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.021/0.021/0.021 ms

bruno@lenovo: compose-net$ docker exec -ti 0f734f3eca10 ping -c 1 9c8c035f9290
ping: bad address '9c8c035f9290'

bruno@lenovo: compose-net$ docker exec -ti 0f734f3eca10 ping -c 1 0f734f3eca10
PING 0f734f3eca10 (172.20.0.3): 56 data bytes
64 bytes from 172.20.0.3: seq=0 ttl=64 time=0.047 ms

--- 0f734f3eca10 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.047/0.047/0.047 ms
```

As you can see above, these are the scenarios that fail:

 1. pinging 0f734f3eca10 from 9c8c035f9290 fails
 2. pinging 9c8c035f9290 from 0f734f3eca10 fails
 3. pinging 9c8c035f9290 from 9c8c035f9290 fails

I understand that [2] and [3] above perhaps should indeed fail since that container has a specific hostname `master`. But [1] should not happen, and that is what should be fixed.

**Comment by dnephin** [comment]
This works for me:

```
version: "2"

services:
  web:
    image: alpine:3.3
    command: sh -c '
        ifconfig;
        ping -c 2 networking_web_1;
        ping -c 2 web;
        hostname=$$(hostname);
        ping -c 2 $${hostname:0:10}'
```

The problem you're seeing is fixed by #2853, which will be in 1.6.1, and is in the master builds already.

**Comment by brunoborges** [comment]
@dnephin thank you.

I did the same tests and all passed with Docker Compose 1.7 built from master commit 77cf67b
