### ISSUE TITLE
Binary on darwin fails with "illegal instruction" on some machines

### ISSUE THREAD

**Issue by tomstuart** [docker/compose#271]
The current `fig` release doesn’t work for me:

```
$ fig
-bash: fig: command not found

$ curl -L https://github.com/orchardup/fig/releases/download/0.4.2/darwin > /usr/local/bin/fig
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   329  100   329    0     0    329      0  0:00:01 --:--:--  0:00:01   329
100 3860k  100 3860k    0     0   625k      0  0:00:06  0:00:06 --:--:--  842k

$ chmod +x /usr/local/bin/fig

$ fig
Illegal instruction: 4
```

I’m running OS X 10.9.3 on a 1.6 GHz Intel Core 2 Duo (Late 2010 MacBook Air).

**Comment by pwaller** [comment]
We hit this over here, too.

**Comment by ramschmaerchen** [comment]
I'd really love to see docker-compose working on vanilla OSX.

fig: 1.1.0-rc2
python: 2.7.5
OS X: 10.9.5

Model Name: MacBook
Model Identifier: MacBook5,2 (Early 2009)
Processor Name: Intel Core 2 Duo
Processor Speed: 2 GHz
Number of Processors: 1
Total Number of Cores: 2
L2 Cache: 3 MB
Memory: 4 GB
Bus Speed: 1.07 GHz

**Comment by NodeGuy** [comment]
:+1:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro5,4
  Processor Name:	Intel Core 2 Duo
  Processor Speed:	2.53 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache:	3 MB
  Memory:	4 GB
  Bus Speed:	1.07 GHz
  Boot ROM Version:	MBP53.00AC.B03
  SMC Version (system):	1.49f2

**Comment by tim545** [comment]
$ sysctl -n machdep.cpu.brand_string
Intel(R) Core(TM) i7 CPU       M 640  @ 2.80GHz

Had the same issue but 
`brew install python`
`pip install -U pip`
fixed it for me

Not sure why but installing python by downloading their package installer (2.7.9) and install Fig with curl gave me the `Illegal instruction: 4` error when running `fig --version`

**Comment by ramschmaerchen** [comment]
"Fixing it" by using 3rd party software is known to work. It also works if I start virtualbox and install debian in it.

**Comment by kulinski** [comment]
Same issue for me on Yosemite.  I have python installed, but not pip.  Running the fig 1.0.1 binary downloaded from github resulted in an "Illegal instruction: 4".   

To fix it, all I had to do was install pip and then that same fig binary worked.  Didn't even need to run "pip install fig" - just executed the fig binary again and the error didn't happen.

I'm doubtful that this is a hardware specific issue.  Isn't it more likely that pip installed/updated some library that the raw fig binary depends on?

Has anyone ever been able to run the fig binary, without having pip already installed?  Its fairly common to have pip these days...

**Comment by aanand** [comment]
@kulinski Are you absolutely certain you ran the same binary before and after?

**Comment by ramschmaerchen** [comment]
@kulinski 's way is not working, at least not on my machine.

Note: docker-compose = fig

Steps:
* virtualenv'ed python
* installed pip
* DL latest fig release
* Mv fig to virtualenv
* Run fig
* `Illegal instruction: 4`

**Comment by josephpage** [comment]
+1 

```bash
$ docker-compose
Illegal instruction: 4
```

Model : MacBookPro5,5 (13" mid-2009 - Core 2 Duo)
OS : 10.10.2
Python : 2.7.6

But docker-compose works fine on my iMac :
Model : iMac12,2 (27" mid-2011 - Core i5)
OS : 10.9.5
Python : 2.7.5

**Comment by voluntaryistonly** [comment]
tryin to build bytecoin using instructions here: http://bytecoin.org/mac-download?binaries
failing with "Illegal instruction: 4" tried to fix using:
brew install python; pip install fig, still no joy 
machine details: 
Mac mini 2009
Processor  2 GHz Intel Core 2 Duo
Memory  5 GB 1067 MHz DDR3
Graphics  NVIDIA GeForce 9400 256 MB
oftware  OS X 10.9.5 (13F34)

**Comment by dperetti** [comment]
Same problem here.
Fig is working. Docker 1.5 working.
Just installed docker-compose latest and get Illegal Instruction: 4.
Mac Pro 2009 . Yosemite 10.10.2.

**Comment by josephpage** [comment]
After rc2, the same with 1.1 release. :cry:

**Comment by BrendanBerkley** [comment]
+1. Fig had worked fine, but the transition to docker-compose was pretty rough. Doing it through pip worked - some combination of removing the curl'd file, installing brew, upgrading things, running pip install, and restarting the terminal.

Model Name:	MacBook Pro (this is the mid-late 2007 model. Running 10.10.1.)
Model Identifier:	MacBookPro3,1
Processor Name:	Intel Core 2 Duo
Processor Speed:	2.4 GHz
Number of Processors:	1
Total Number of Cores:	2
L2 Cache:	4 MB
Memory:	4 GB
Bus Speed:	800 MHz
Boot ROM Version:	MBP31.0070.B07
SMC Version (system):	1.16f11

**Comment by toriaezunama** [comment]
+1. Illegal Instruction: 4.
Model Name:	MacBook
  Model Identifier:	MacBook6,1
  Processor Name:	Intel Core 2 Duo
  Processor Speed:	2.26 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache:	3 MB
  Memory:	8 GB
  Bus Speed:	1.07 GHz
  Boot ROM Version:	MB61.00C8.B00
  SMC Version (system):	1.51f53

**Comment by EloB** [comment]
+1

MacBook Pro "Core i5" 2.53 15" Mid-2010
2.53 GHz Core i5 (I5-540M)
Model ID:	MacBookPro6,2

Works when installing from `brew` but I would like to try the new prerelease. https://github.com/docker/compose/releases/tag/1.2.0rc1 but then I get `Illegal Instruction: 4`.

**Comment by josephpage** [comment]
@EloB docker-compose 1.1.0 works perfectly on older Macs when installing with `pip install docker-compose`

Can you try `sudo pip install -U https://github.com/docker/compose/archive/1.2.0rc1.zip` ?

**Comment by ramschmaerchen** [comment]
As far as I know, OSX does not ship with pip.

**Comment by josephpage** [comment]
So you can try this, but it seems some dependencies need to be updated with pip :
```
git clone https://github.com/docker/compose.git
cd compose
sudo python setup.py install
```

Or install pip with brew : `brew install python` which updates shipped Python binaries and installs pip.

**Comment by EloB** [comment]
Thanks installing with `pip` worked! :)

**Comment by jdmarshall** [comment]
I have an old machine I'm trying to set up as a Docker host.  It would be good to get this problem identified so I don't have to install a bunch of otherwise unused dependencies.  

The discussion this far implies this is something new to 1.2 but I've verified that the problem also happens in 1.1

**Comment by haggen** [comment]
Using the binary throws:
```
[1]    10956 illegal hardware instruction  docker-compose
```

And after installing from pip (with python 3.4.3), it throws:
```
Traceback (most recent call last):
  File "/Users/Arthur/.pyenv/versions/3.4.3/lib/python3.4/site-packages/pkg_resources/__init__.py", line 612, in _build_master
    ws.require(__requires__)
  File "/Users/Arthur/.pyenv/versions/3.4.3/lib/python3.4/site-packages/pkg_resources/__init__.py", line 918, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/Arthur/.pyenv/versions/3.4.3/lib/python3.4/site-packages/pkg_resources/__init__.py", line 810, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (requests 2.4.3 (/Users/Arthur/.pyenv/versions/3.4.3/lib/python3.4/site-packages), Requirement.parse('requests>=2.5.2'), {'docker-py'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Arthur/.pyenv/versions/3.4.3/bin/docker-compose", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/Users/Arthur/.pyenv/versions/3.4.3/lib/python3.4/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/Users/Arthur/.pyenv/versions/3.4.3/lib/python3.4/site-packages/pkg_resources/__init__.py", line 614, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Users/Arthur/.pyenv/versions/3.4.3/lib/python3.4/site-packages/pkg_resources/__init__.py", line 627, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Users/Arthur/.pyenv/versions/3.4.3/lib/python3.4/site-packages/pkg_resources/__init__.py", line 810, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (requests 2.4.3 (/Users/Arthur/.pyenv/versions/3.4.3/lib/python3.4/site-packages), Requirement.parse('requests>=2.5.2'), {'docker-py'})

```

I'm using an iMac with Yosemite, and I'd like to use docker-compose you know :/

**Comment by rfranca86** [comment]
Hi Haggen,

You should try update requests package try to use 'pip install --upgrade requests==2.5.2' and install docker-py too

**Comment by haggen** [comment]
@rfranca86 I got it working by using `python 2.7.9`, then simply `pip install docker-compose` and done! But I'm gonna try what you say later, thanks!

**Comment by marcio0** [comment]
Installing via `pip` worked for me too.

**Comment by bparanj** [comment]
When running docker compose on Mac OS 10.7.5 (Mac Pro Mid 2010)
Error:
Illegal instruction: 4

Fix:
brew install python
pip install docker-compose

Does not work. Re-installing using 

curl -L https://github.com/docker/compose/releases/download/1.2.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

also does not work.

**Comment by bparanj** [comment]
Download https://www.python.org/ftp/python/2.7.9/python-2.7.9-macosx10.6.pkg installer.
Install Python 2.7.9
pip install docker-compose also fails.

**Comment by mwcampbell** [comment]
This is happening because by default, Homebrew builds Python with all of the optimizations that the build machine can support. Assuming the build is happening on a Mac with a Sandy Bridge or newer processor, those optimizations will include the use of AVX instructions. So the solution is to configure Homebrew to only use safe optimizations; I'd suggest "-O2 -fno-omit-frame-pointer" and nothing more.

**Comment by joernroeder** [comment]
pip installed successfully but i've got the following error while starting docker-compose:

    $ docker-compose up
    Traceback (most recent call last):
      File "/usr/local/bin/docker-compose", line 5, in <module>
        from pkg_resources import load_entry_point

**Comment by joernroeder** [comment]
i've updated to `docker-compose 1.3.1` which fixed my issues.

**Comment by Telemakhos** [comment]
cURL install method is not working for everyone as it seems... I also get the

Error:
Illegal instruction: 4

Funny thing is that I was going to install first with pip... Why not advertise pip as the default install method? Whatever...

**Comment by burnash** [comment]
Installed 1.3.3 (latest release) with curl and getting this error:
~~~
$ docker-compose up
Illegal instruction: 4
~~~

OS X 10.9.5 MBP Late 2008

**Comment by apoigne** [comment]
I struggled for two days and finally got. it. Use home-brew:

brew install docker
brew install docker-compose

but take care to get rid of whatever you installed beforehand and, may be, use

brew link --force openssl

but I am not sure whether the latter is necessary.

Got the idea because somebody somewhere stated that home-brew does not provide docker-compose

OSX 10.10.4 MBP Late 2007

**Comment by burnash** [comment]
Thanks, @apoigne. Your solution did work for me.

**Comment by apoigne** [comment]
You are welcome

Axel

**Comment by ramschmaerchen** [comment]
Does anyone care to read the thread? This one is going in circles. It was "always" working with non-vanilla solutions like brew. This is not why this thread was created. It was created MORE THAN A YEAR AGO to highlight it non-working on VANILLA OSX.

**Comment by lc3t35** [comment]
I  followed @josephpage and installed docker-compose from source : 
````
$ git clone https://github.com/docker/compose.git
$ cd compose
$ sudo python setup.py install
$ docker-compose --version
docker-compose version: 1.4.0dev
````

**Comment by ramschmaerchen** [comment]
@aanand it would be great if we had specific system requirements in terms of software / libraries. A lot of people posted their specs here. Do we have any idea why it does not work exactly? Sorry if I missed them if we do.

**Comment by mwcampbell** [comment]
Yes, we do know why it doesn't work. As I posted earlier, the problem is that the Compose binary package for OS X uses the Python package from Homebrew. By default, Homebrew enables all of the CPU-specific compiler optimizations that are supported by the processor on the build machine. Specifically, assuming the build is done on a Mac with a Sandy Bridge or later processor, the version of Python compiled by Homebrew will use AVX. So the solution is to configure Homebrew at build time to use a more conservative set of optimizations. Someone needs to figure out how to do this in the Compose build scripts for OS X.

**Comment by aanand** [comment]
Thanks @mwcampbell. This is the Homebrew formula we use:

https://raw.githubusercontent.com/Homebrew/homebrew/1681e193e4d91c9620c4901efd4458d9b6fcda8e/Library/Formula/python.rb

I'm not sure how to configure Homebrew to disable AVX optimizations.

I have determined the CFLAGS passed when compiling Python:

```
$ /usr/local/bin/python
Python 2.7.9 (default, May  2 2015, 03:33:28) 
[GCC 4.2.1 Compatible Apple LLVM 5.1 (clang-503.0.40)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sysconfig
>>> sysconfig.get_config_var('CFLAGS')
'-fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes'
```

But I'm not sure which, if any of those, are the culprits, or how to disable them. Other than just downloading Python and compiling it ourselves. Certainly an option.

**Comment by Coaxial** [comment]
Came here to say +1.

Fixed it by uninstalling docker, boot2docker and fig, installing dockertoolbox, running it so the default machine gets initialized, remove dockertoolbox and install docker, docker-compose and docker-machine. Not the way it should be but at least it works on my MacbookPro5,3

```
brew remove docker boot2docker fig
brew cask install dockertoolbox
# run the docker toolbox app to initialize the default machine
brew cask remove dockertoolbox
brew cask install docker docker-compose docker-machine
```

**Comment by dacz** [comment]
@Coaxial 
Error: No available Cask for docker. Did you mean one of:
boot2docker	    boot2docker-status	docker-compose	    docker-machine	dockertoolbox

**Comment by Coaxial** [comment]
@dacz my bad, it should be `brew install docker docker-compose docker-machine`

**Comment by claytonmarinho** [comment]
Fixed after install compose with pip (osx 10.11)
sudo pip install -U docker-compose

**Comment by GabLeRoux** [comment]
I had same problem on a Macbook Pro Mid 2010, 

I had the problem by installing from toolbox, I then tried the 1.4.2 version from `brew install docker-compose` and manual install, but still failing.

I confirm this works:
```
sudo pip install -U docker-compose
```
> Successfully installed PyYAML-3.11 docker-compose-1.4.2 docker-py-1.3.1 dockerpty-0.3.4 docopt-0.6.2 requests-2.6.2 six-1.10.0 texttable-0.8.3 websocket-client-0.32.0

**Comment by antek-drzewiecki** [comment]
`sudo pip install -U docker-compose` fails for me. 
Getting python errors now:
```
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
```

**Comment by dnephin** [comment]
Our new ["install using pip" instructions](https://github.com/docker/compose/blob/master/docs/install.md#install-using-pip) suggest using a virtualenv to mitigate problems like this.

@antek-drzewiecki (or anyone else that hit this issue) I'd like to see if the binaries we build on travis have this same issue. If you have a minute could you try the master build: https://dl.bintray.com/docker-compose/master/docker-compose-Darwin-x86_64 and let me know if you get the same error.

Thanks!

**Comment by antek-drzewiecki** [comment]
@dnephin I got my dependencies solved now. So it's not like I'm on a clean install anymore.
I will uninstall the docker-compose pip and use the darwin binary you linked. 
I'll update the comment within an hour with the results ;)

**Comment by dnephin** [comment]
@antek-drzewiecki Thank you for trying it out!  I think we should use these binaries for the release from now on.

**Comment by dduportal** [comment]
@dnephin : It works on my config also :
* Hackintosh on El Capitan 10.10
* CPU : Core i7-950 (before Sandy bridge so)

Thanks for solving that, hope you'll have time to integrate in the 1.5.0 release :)

**Comment by kolis** [comment]
Same problem with docker toolbox 1.9 relase, on Mac OS X, running on a 2008 MacPro.

Are the binarys compiled with instruction set which excludes some older CPUs maybe?

**Comment by dnephin** [comment]
@kolis Does the binary from https://dl.bintray.com/docker-compose/master/ work for you?

What version of OSX are you running?

**Comment by dolhana** [comment]
I encountered the same problem after updating docker toolbox to 1.9.

The binary downloaded from https://dl.bintray.com/docker-compose/master/ solved the problem.

OS X 10.11.1 El Capitan
MacBook Pro 15 Mid 2010

**Comment by kolis** [comment]
Yes, the bintray version works fine, running OS X 10.11.1 (15B42)

**Comment by dduportal** [comment]
For information, it is working fine with my config :
```
$ ./docker-compose-Darwin-x86_64 -version
docker-compose version: 1.6.0dev
$ sysctl -n machdep.cpu.brand_string
Intel(R) Core(TM) i7 CPU         950  @ 3.07GHz
```

BTW I'm on OS X 10.11 and have the latest toolbox (1.9.0c) installed.

@dnephin : what is the integration plan ? Release 1.6.0 ?

Thanks for the fix !

**Comment by mdtusz** [comment]
Any progress on this? Still having the error crop up when installed with `brew cask` on a mid 09 MacBook running Yosemite 10.10.5.

**Comment by marcio0** [comment]
Installing using `pip` works for me.

**Comment by janeczku** [comment]
https://github.com/docker/compose/releases/download/1.5.2/docker-compose-Darwin-x86_64

=> illegal hardware instruction

https://dl.bintray.com/docker-compose/master/:docker-compose-Darwin-x86_64

=> WORKING

**Comment by kolis** [comment]
Same problem in 1.6 release of docker-compose, and again, the bintray binary works

**Comment by jayfk** [comment]
Same here. Running a Mac Pro 5,1 with 10.11.2. Bintray works.

**Comment by schmunk42** [comment]
We see this on `OS X 10.10.5`

**Comment by jayfk** [comment]
> Running a Mac Pro 5,1 with 10.11.2. Bintray works.

`1.6.0` in docker-toolbox is still broken.

**Comment by jdmarshall** [comment]
Can we at least change the download and install instructions on the main website?  It's silly to have official how-to's that don't work.

**Comment by jmreicha** [comment]
Just ran across this. `OS X 10.11.3`,`MacBook Pro (15-inch, Mid 2010)`.

**Comment by web-bert** [comment]
Just installed on OS X 10.11.3 on a MacBook Pro (15-inch, 2.53GHz, Mid 2009) and I get the "Illegal instruction: 4"

**Comment by Elhodred** [comment]
I solved the issue without homebrew in this way:

first, download python official package from here: https://www.python.org/downloads/
will update local python and install pip. Now, in a new terminal session

```
sudo pip install fig
sudo pip uninstall docker-compose
sudo pip install —upgrade docker-compose
hash -r
```

**Comment by web-bert** [comment]
@Elhodred Which version of Python? 2 or 3?

**Comment by Elhodred** [comment]
Python 2

**Comment by ozlerhakan** [comment]
Thanks @Elhodred it works!

**Comment by mattolson** [comment]
Just ran into this on a mid-2010 Macbook pro

```
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro6,2
  Processor Name:	Intel Core i7
  Processor Speed:	2.66 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	4 MB
  Memory:	8 GB
  Processor Interconnect Speed:	4.8 GT/s
  Boot ROM Version:	MBP61.0057.B11
  SMC Version (system):	1.58f17
```

**Comment by aanand** [comment]
This should now be fixed in the [1.7.0 release candidate](https://github.com/docker/compose/releases/download/1.7.0-rc1).

**Comment by aanand** [comment]
Apologies, that link's broken. Correct URL:

https://github.com/docker/compose/releases/tag/1.7.0-rc1

**Comment by aanand** [comment]
Can anyone who's experienced this issue confirm whether or not the 1.7.0-rc1 binary fixes the issue for them?

**Comment by ozlerhakan** [comment]
yes @aanand it is now fixed. Thanks!

**Comment by dduportal** [comment]
Hello @aanand ! Thanks for fixing that !

i7 950 with El Capitan 10.11.2 and i3 540 with 10.9.4 tested : success !

**Comment by sincraianul** [comment]
Fix is working on iMac (Mid 2010). Thanks @aanand. :)

**Comment by WidgetsBurritos** [comment]
I can confirm it works in 1.7.0-rc1 and 1.7.0-rc2 on my Mac mini (Mid 2010).  Thank you!

**Comment by destijl** [comment]
@aanand I have a similar problem with my own software: we build on new macs but it needs to work on old ones. Your bug is pretty much the top google hit for "Illegal instruction: 4" :) Can you provide some details on your solution to enlighten the Internet? Did you just find old hardware to build on? Or set some compile time flags?

**Comment by dnephin** [comment]
We started building on travisci, which fixes it for newer versions of OSX, but it doesn't run on older versions of OSX.
