### ISSUE TITLE
[1.7] CTRL+C fails to stop containers when running compose in the foreground

### ISSUE THREAD

**Issue by nickjj** [docker/compose#3347]
I can't reproduce it but I would say about 10% of the time when I hit CTRL+C, the containers that were started with `docker-compose up` fail to stop. I'll get an ABORT message in the terminal but they are still up. When it works, it says "gracefully stopping..." instead of ABORT.

At this point I need to `docker-compose stop` them to "really" stop them.

It was much worse in earlier versions of Compose but it's still happening often enough that I feel like it needs some attention. If you need more info let me know.
##### System

``` sh
# Distro (it's actually xubuntu, not Ubuntu)
nick@oriath:~ ⚡ lsb_release --all
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:    14.04
Codename:   trusty

# Kernel
nick@oriath:~ ⚡ uname -a
Linux oriath 3.13.0-71-generic #114-Ubuntu SMP Tue Dec 1 02:34:22 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

# Terminal info
nick@oriath:~ ⚡ xfce4-terminal --version
xfce4-terminal 0.6.3 (Xfce 4.10)
```
##### Docker

``` sh
nick@oriath:~ ⚡ docker info
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 187
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 300
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host null
Kernel Version: 3.13.0-71-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 5.877 GiB
Name: oriath
ID: 2P6Z:G7DQ:46LR:WO63:BDMP:ZAPH:XADM:AJNB:2WON:FTQD:RPIY:DYKH
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Username: nickjj
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```
##### Docker Compose

``` sh
nick@oriath:~ ⚡ docker-compose --version
docker-compose version 1.7.0, build 0d7bf73
```
### Potentially relevant information

When I encounter the issue I'm always running multiple containers, such as postgres, redis, and multiple web services. I never run 1 container so I can't say for sure if it would happen with only 1.

It happens with and without using `links` and both the legacy and v2 `docker-compose.yml` files.

**Comment by dnephin** [comment]
See #2904 for some background on the issue

**Comment by Vanuan** [comment]
Is it related to the docker's PID 1 problem?

**Comment by dnephin** [comment]
No, it's an issue with pyinstaller and signal handling.

**Comment by antinescience** [comment]
Hm. I can make this happen reliably 100% of the time on a few of our repositories. If I wanted to help dig in with a fix, any pointers on where to start looking?

**Comment by toby-griffiths** [comment]
Any update on this issue, as I'm having the same problem with `docker-compose version 1.9.0, build 2585387`

**Comment by tterrace** [comment]
Same issue on OSX `docker-compose version 1.10.0, build 4bd6f1a`.

**Comment by nickjj** [comment]
> No, it's an issue with pyinstaller and signal handling.

I think so too.

I just had the same "ABORT" error happen to me while closing out the result of running `docker-compose logs -f`, so it's almost certainly related to the `CTRL+C` signal processing, and not so much the `up` command.

**Comment by dabroz** [comment]
Having the same problem on OSX 10.12.3:
```
docker-compose version 1.11.2, build dfed245
```

**Comment by vmalloc** [comment]
Also getting this on 1.12.0-rc2, build 08dc2a4

**Comment by tristanoneil** [comment]
Seeing this too. On OSX w/ Docker For Mac `17.05.0-ce-rc1-mac8 (16582)`. Details from `docker-compose version`.

```
docker-compose version 1.12.0, build b31ff33
docker-py version: 2.2.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
```

**Comment by amirbehzad** [comment]
Same here under Darwin 16.6.0 and docker-compose version 1.11.2, build dfed245
`^CERROR: Aborting.`

**Comment by amirbehzad** [comment]
Here's a workaround:
https://github.com/docker/compose/issues/3317#issuecomment-209519731

**Comment by AlexanderOMara** [comment]
I'm also getting this issue about 30% of the time, latest Docker for Mac on latest macOS.

The `tty: true` thing also somehow works around the issue for me. I have no idea how or why though.

**Comment by cjerdonek** [comment]
In Dec. 2015, I offered a number of suggestions to make compose's signal handling code easier to check and reason about. This was in issue #2543 starting [here](https://github.com/docker/compose/issues/2543#issuecomment-167647153).

A number of my suggestions were dismissed and don't look like they've been tried or given further consideration. Given that signal-handling continues to be an issue for this project (the issues today look more or less the same as before), I would suggest taking another look at what I suggested.

There are a few things I suggested back then that I think are worth considering in particular:

1. register your signal handlers at the very beginning of the program instead of "on the fly" in the middle of the program execution.
2. make your signal handlers return without raising an exception. This is because asynchronous exceptions have inherent problems in Python.
3. I also provided a pattern for handling a signal being sent more than once.

**Comment by ged15** [comment]
Hello,

Still happening in 1.17. Any plans to fix?

**Comment by camilo0365** [comment]
Still happening in version 1.20.0-rc2 . 😢

**Comment by ilyakamens** [comment]
Happening for me too.
```
$ docker-compose version
docker-compose version 1.18.0, build 8dd22a9
docker-py version: 2.6.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016

$ docker --version
Docker version 17.12.0-ce, build c97c6d6
```

OS X version `10.13.3 (17D102)`

**Comment by bakku** [comment]
Here too on `Docker for Mac`:

```
docker-compose version 1.20.1, build 5d8c71b
docker-py version: 3.1.4
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2n  7 Dec 2017
```

**Comment by damouse** [comment]
Same on OSX 10.13.1
Docker Version 18.03.1-ce-mac65 (24312)
docker-compose version 1.21.1, build 5a3f1a3
docker-py version: 3.3.0
CPython version: 3.6.4

`tty: true` did not help.

**Comment by nhanft** [comment]
It's still happening :I
```Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: true

docker-compose version 1.21.1, build 5a3f1a3
docker-py version: 3.3.0
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018
```

**Comment by Vanuan** [comment]
Could you all please confirm what exactly is still happening when you hit CTRL+C?
I haven't seen "ABORT" message for a year.

**Comment by dylancopeland** [comment]
After running `docker-compose up` and sending CTRL+C, here's what is output:

`^CERROR: Aborting.`

**Comment by Vanuan** [comment]
Ok, so there's still "an issue with pyinstaller and signal handling". Here's a statement from @dnephin : 
> pyinstaller raises thread.error for some unknown reasons (probably a bug in pyinstaller)

So this is an upstream issue, not in issue with docker-compose per se:
https://github.com/pyinstaller/pyinstaller/issues/208

**Comment by Vanuan** [comment]
Ok, so as a workaround we can install docker-compose from pypi:
https://pypi.org/project/docker-compose/#history

```
pip install docker-compose
```

**Comment by MythicManiac** [comment]
I'm working with Docker on two machines, both Windows and running version 18.06.1-ce-win73. On one machine Ctrl-C never killis the containers, whereas on the second machine it always works as intended.

If anyone has suggestions on what differences should I look for between the machines, I'm all ears.

**Comment by CSammy** [comment]
The issue may be fixed with https://github.com/pyinstaller/pyinstaller/pull/3151 which was merged in August, latest release of pyinstaller is [v3.4](https://github.com/pyinstaller/pyinstaller/releases/tag/v3.4) in September.

Without regressions, changing the file https://github.com/docker/compose/blob/master/requirements-build.txt should fix this issue if I am right. I'd prefer someone familiar with the project do a PR rather than myself though.

**Comment by MythicManiac** [comment]
What fixed this for me was updating git bash on Windows, which is what I was running the docker commands on. My original issue seems unrelevant to the topic here, but maybe some folks with the same issue will end up here from google so posting anyway.

**Comment by bfirsh** [comment]
This is still the one issue I am running into daily using Compose.

https://github.com/docker/compose/pull/6518 has bumped pyinstaller to 3.4. I wonder if this fixes this, or do we have to add `--bootloader-ignore-signals`?

**Comment by ulyssessouza** [comment]
@bfirsh The change introduced by https://github.com/pyinstaller/pyinstaller/pull/3515 is activated only if  `--bootloader-ignore-signals` is present, so the bump in #6518 didn't address to this issue.

The flag solution LGTM since the change looks functionally inoffensive and passed the tests on my machine.

@cheungpat would you like to propose a PR based on https://github.com/cheungpat/compose/commit/a986cc9166d4d8992d38eca84d76bbfd06c85f70 ?

**Comment by torarnv** [comment]
Upgraded to 1.24.0 with the `curl` instructions in https://github.com/docker/compose/releases/tag/1.24.0

I'm still seeing this:
```
home-assistant    | 2019-06-23 20:58:55 INFO (SyncWorker_1) [homeassistant.loader] Loaded mqtt from homeassistant.components.mqtt
^CERROR: Aborting.
```

```
❯ docker-compose -v
docker-compose version 1.24.0, build 0aa59064
```

**Comment by torarnv** [comment]
Adding `tty: true` does not seem to help

**Comment by chris-crone** [comment]
@torarnv I'm not sure that the fix was merged into 1.24. Can you try with [1.25.0-rc1](https://github.com/docker/compose/releases/tag/1.25.0-rc1)?

**Comment by gromilQaaaa** [comment]
1.25 has the same problem on ubuntu for me

**Comment by inieves** [comment]
I am seeing this problem still:
docker-compose version 1.29.2, build 5becea4
on macOS

**Comment by inieves** [comment]
I am noticing (what seems to be) a failure by Python to parse a docker source file from docker-compose, when control-c is pressed (triggering a graceful shutdown).

I was able to capture this verbose debug output from the moment just after control-c was pressed.  I was able to trigger this failed graceful shutdown output after having about 10 successful graceful shutdowns.  The most relevant part seems to be the last (approximately) 4 lines:

Also, there seems to be an open Python bug that relates quite strongly to this failure behavior:
https://bugs.python.org/issue18961

=============================

^CGracefully stopping... (press Ctrl+C again to force)
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=False, filters={'label': ['com.docker.compose.project=stuco_dev-route', 'com.docker.compose.oneoff=False']})
--- Logging error ---
Traceback (most recent call last):
  File "compose/cli/main.py", line 1530, in up_shutdown_context
  File "compose/cli/main.py", line 1216, in up
  File "compose/cli/log_printer.py", line 88, in run
  File "compose/cli/log_printer.py", line 241, in consume_queue
  File "queue.py", line 180, in get
  File "threading.py", line 316, in wait
  File "compose/cli/signals.py", line 15, in shutdown
compose.cli.signals.ShutdownException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging/__init__.py", line 1082, in emit
  File "compose/cli/signals.py", line 15, in shutdown
compose.cli.signals.ShutdownException
Call stack:
Traceback (most recent call last):
  File "compose/cli/main.py", line 1530, in up_shutdown_context
  File "compose/cli/main.py", line 1216, in up
  File "compose/cli/log_printer.py", line 88, in run
  File "compose/cli/log_printer.py", line 241, in consume_queue
  File "queue.py", line 180, in get
  File "threading.py", line 316, in wait
  File "compose/cli/signals.py", line 15, in shutdown
compose.cli.signals.ShutdownException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging/__init__.py", line 1082, in emit
  File "compose/cli/signals.py", line 15, in shutdown
compose.cli.signals.ShutdownException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tokenize.py", line 330, in find_cookie
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 0: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 203, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 1229, in up
  File "contextlib.py", line 135, in __exit__
  File "compose/cli/main.py", line 1533, in up_shutdown_context
  File "compose/project.py", line 411, in stop
  File "compose/project.py", line 854, in containers
  File "compose/project.py", line 834, in _labeled_containers
  File "compose/cli/verbose_proxy.py", line 45, in proxy_callable
  File "logging/__init__.py", line 1434, in info
  File "logging/__init__.py", line 1577, in _log
  File "logging/__init__.py", line 1587, in handle
  File "logging/__init__.py", line 1649, in callHandlers
  File "logging/__init__.py", line 948, in handle
  File "logging/__init__.py", line 1087, in emit
  File "logging/__init__.py", line 1010, in handleError
  File "/Users/administrator/jenkins/workspace/dsg_compose_1.29.2/build/toolchain/Frameworks/Python.framework/Versions/3.9/lib/python3.9/traceback.py", line 190, in print_stack
  File "/Users/administrator/jenkins/workspace/dsg_compose_1.29.2/build/toolchain/Frameworks/Python.framework/Versions/3.9/lib/python3.9/traceback.py", line 211, in extract_stack
  File "/Users/administrator/jenkins/workspace/dsg_compose_1.29.2/build/toolchain/Frameworks/Python.framework/Versions/3.9/lib/python3.9/traceback.py", line 366, in extract
  File "/Users/administrator/jenkins/workspace/dsg_compose_1.29.2/build/toolchain/Frameworks/Python.framework/Versions/3.9/lib/python3.9/traceback.py", line 288, in line
  File "/Users/administrator/jenkins/workspace/dsg_compose_1.29.2/build/toolchain/Frameworks/Python.framework/Versions/3.9/lib/python3.9/linecache.py", line 30, in getline
  File "/Users/administrator/jenkins/workspace/dsg_compose_1.29.2/build/toolchain/Frameworks/Python.framework/Versions/3.9/lib/python3.9/linecache.py", line 46, in getlines
  File "/Users/administrator/jenkins/workspace/dsg_compose_1.29.2/build/toolchain/Frameworks/Python.framework/Versions/3.9/lib/python3.9/linecache.py", line 136, in updatecache
  File "tokenize.py", line 394, in open
  File "tokenize.py", line 371, in detect_encoding
  File "tokenize.py", line 335, in find_cookie
SyntaxError: invalid or missing encoding declaration for '/Applications/Docker.app/Contents/Resources/bin/docker-compose-v1/docker-compose'
[48682] Failed to execute script docker-compose

**Comment by chris-crone** [comment]
Hi @inieves! Have you tried Compose v2 and been able to reproduce the issue with that?

**Comment by inieves** [comment]
> Hi @inieves! Have you tried Compose v2 and been able to reproduce the issue with that?

I will look into that now.  Thanks for the recommendation.

**Comment by inieves** [comment]
Using docker-compose version 2.0.0 I have experimented further (starting up and then attempting to gracefully shutdown with verbose logging), and I find a similar failure mode with the following error output:

^CGracefully stopping... (press Ctrl+C again to force)
DEBU[0001] FIXME: Got an status-code for which error does not match any expected type!!!: -1 module=api status_code=-1
DEBU[0001] FIXME: Got an status-code for which error does not match any expected type!!!: -1 module=api status_code=-1
canceled

**Comment by chris-crone** [comment]
What are you expecting to happen?

It might be that your containers don't have an init or something that catches `SIGINT` (what is sent by the graceful shutdown) and so need to be sent `SIGKILL` (what is sent when you force). You could try adding [this](https://github.com/compose-spec/compose-spec/blob/master/spec.md#init) to the services that are not being properly stopped.

**Comment by inieves** [comment]
I just updated my comment above (compose v2) because I may have initiated the graceful shutdown before the startup process was complete.

That said...

I am expecting graceful shutdown to _start_ 100% of the time control-c is pressed.  At this point, it seems to start 90% of the time because 10% of the time graceful shutdown does not even start.  By start I mean that my containers receive SIGINT.

All 3 of my containers do have init, and the init is running as PID 1.  Interestingly, all 3 of my containers are still running after the graceful shutdown failure which occurs 10% of the time.  This leads me to believe that docker-compose actually fails before it sends the signals to my containers. (at least in the case of docker compose v1)

I am continuing to hammer away with compose v2.

Your input and feedback so far have been super helpful as avenues for me to investigate.

**Comment by inieves** [comment]
... so far compose v2 seems more robust.

Thanks for that tip/workaround @chris-crone 

I will leave this issue/thread/bug open still for the sake of compose v1 in which the issue seems to exist.

**Comment by chris-crone** [comment]
Glad to hear that v2 is better! If you run into issues with it not doing what's expected, please do create a new issue

**Comment by shyed2001** [comment]
https://stackoverflow.com/questions/31350335/docker-not-responding-to-ctrlc-in-terminal
