### ISSUE TITLE
Bug when merging ports with service inheritance and python 3.6 

### ISSUE THREAD

**Issue by jggc** [docker/compose#4876]
When merging two files defining the same service with python 3.6, and the head defines both host and container port but the base defines only the container port, I get the following error : 

```
(python3/6) docker-compose -f docker-compose-base.yml -f docker-compose-head.yml config
Traceback (most recent call last):
  File "/tmp/venv/bin/docker-compose", line 11, in <module>
    sys.exit(main())
  File "/tmp/venv/lib/python3.6/site-packages/compose/cli/main.py", line 68, in main
    command()
  File "/tmp/venv/lib/python3.6/site-packages/compose/cli/main.py", line 112, in perform_command
    handler(command, options, command_options)
  File "/tmp/venv/lib/python3.6/site-packages/compose/cli/main.py", line 289, in config
    compose_config = get_config_from_options(self.project_dir, config_options)
  File "/tmp/venv/lib/python3.6/site-packages/compose/cli/command.py", line 47, in get_config_from_options
    config.find(base_dir, config_path, environment)
  File "/tmp/venv/lib/python3.6/site-packages/compose/config/config.py", line 337, in load
    service_dicts = load_services(config_details, main_file)
  File "/tmp/venv/lib/python3.6/site-packages/compose/config/config.py", line 459, in load_services
    service_config = merge_services(service_config, next_config)
  File "/tmp/venv/lib/python3.6/site-packages/compose/config/config.py", line 450, in merge_services
    for name in all_service_names
  File "/tmp/venv/lib/python3.6/site-packages/compose/config/config.py", line 450, in <dictcomp>
    for name in all_service_names
  File "/tmp/venv/lib/python3.6/site-packages/compose/config/config.py", line 823, in merge_service_dicts_from_files
    new_service = merge_service_dicts(base, override, version)
  File "/tmp/venv/lib/python3.6/site-packages/compose/config/config.py", line 898, in merge_service_dicts
    merge_ports(md, base, override)
  File "/tmp/venv/lib/python3.6/site-packages/compose/config/config.py", line 931, in merge_ports
    md[field] = [item for item in sorted(merged.values())]
TypeError: '<' not supported between instances of 'str' and 'NoneType'
```
But with python 2.7 it works even though it's not merging properly but rather appending : 
```
(python2.7) docker-compose -f docker-compose-base.yml -f docker-compose-head.yml config
networks: {}
services:
  test:
    image: nginx
    ports:
    - 80/tcp
    - 8080:80/tcp
version: '2.0'
volumes: {}
```

And the minimal content of the files : 

docker-compose-base.yml 
```
version: '2'

services:
    test:
        image: nginx
        ports:
            - '80'
```
docker-compose-head.yml 
```
version: '2'

services:
    test:
        image: nginx
        ports:
            - '8080:80'
```

**Comment by shin-** [comment]
What is the output of `docker-compose version` ? I seem to remember we fixed something similar recently.

**Comment by jrocketfingers** [comment]
@shin- 
```
docker-compose version 1.12.0, build unknown
docker-py version: 2.2.1
CPython version: 3.6.1
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

I'm having the same issue right now, trying to override specified ports (e.g. 80, with 80:80) with `docker-compose.override.yml`.

**Comment by shin-** [comment]
Can you try the 1.14 RC from our releases page and check if the issue persists?

**Comment by pavlepredic** [comment]
Changing 
`md[field] = [item for item in sorted(merged.values())]`
to
`md[field] = [item for item in merged.values()]`
seems to fix the issue. No idea if it has side effects.
https://github.com/docker/compose/blob/master/compose/config/config.py#L957
to

**Comment by cybe** [comment]
I'm likely affected by the same bug in a similar scenario: When using two identical port definitions that only differ in protocol, one gets lost:

testcase.yml:
```
version: '3.2'
services:
  testcase:
    image: alpine
    ports:
      - "1234/tcp"
      - "1234/udp"
```

empty.yml:
```
version: '3.2'
```

Working as expected: `docker-compose-1.14.0-rc2 -f testcase.yml config`
```
services:
  testcase:
    image: alpine
    ports:
    - protocol: tcp
      target: 1234
    - protocol: udp
      target: 1234
version: '3.2'
```

Using both configs, one protocol is missing: `docker-compose-1.14.0-rc2 -f testcase.yml -f empty.yml config `
```
services:
  testcase:
    image: alpine
    ports:
    - protocol: udp
      target: 1234
version: '3.2'
```

If this is a different bug, I'm happy to open a separate issue.

**Comment by shin-** [comment]
@cybe Yes, that would be a different bug (although I'm not sure it's supposed to work? Regardless, a separate issue is warranted)

**Comment by OwlyCode** [comment]
I had the exact same problem as @jggc . I installed `1.14.0-rc2` and the problem is gone, no more python error (python 3.6).

**Comment by cybe** [comment]
@shin- My issue was part of #4912, which is already fixed by #4913.

**Comment by shin-** [comment]
I'm going to close this as I believe all issues mentioned in the thread will be fixed by 1.14.0.

**Comment by pavlepredic** [comment]
Still getting this error with `1.14.0`. Is it fixed for you @jggc?

**Comment by pavlepredic** [comment]
...and I'm still able to fix it with this hack: https://github.com/docker/compose/issues/4876#issuecomment-305453395

**Comment by shin-** [comment]
@pavlepredic Thanks - #4955 should fix this.
