### ISSUE TITLE
docker-compose cli command eat previous lines from the console output

### ISSUE THREAD

**Issue by bscheshirwork** [docker/compose#5627]
```sh
$docker-compose -f ~/docker-codeception-run/docker-compose.yml up -d
```
will rewrite existing output by produced output
![peek 2018-01-30 16-51](https://user-images.githubusercontent.com/5769211/35569799-3c577736-05de-11e8-95b9-3ca488e272df.gif)

**Comment by shin-** [comment]
Thanks for the report!

**Comment by ghostsquad** [comment]
what version of compose?

**Comment by bscheshirwork** [comment]
this happens after update to https://github.com/docker/compose/releases/tag/1.19.0-rc2.

**Comment by bscheshirwork** [comment]
`docker-compose version 1.19.0-rc3, build cdd0282`
pacman still alive!

**Comment by Greek64** [comment]
Ha, yeah. Just wanted to search if an issue about this already exists. +1

Even if it's just cosmetic, it is driving me crazy! (only happens on up command)

**Comment by ghostsquad** [comment]
@Greek64 Ya, I thought it was really weird that up & down have different behavior. It seems they should be using the same code paths, and honestly that's probably the fix.

**Comment by bscheshirwork** [comment]
So... I try to detect commit (I am not a python programmer)

The eater was called between versions 1.17.0 and 1.18.0 (see half check) but error is older: after add colors (and status) the `docker-compose up` process draw 2 line.

```sh
dev@dev-Aspire-V3-772:~$ curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   617    0   617    0     0    749      0 --:--:-- --:--:-- --:--:--   749
100 8066k  100 8066k    0     0  1583k      0  0:00:05  0:00:05 --:--:-- 2050k
dev@dev-Aspire-V3-772:~$ chmod +x /usr/local/bin/docker-compose
dev@dev-Aspire-V3-772:~$ docker-compose -f ~/projects/docker-yii2-app-advanced/docker-codeception-run/docker-compose.yml down
Stopping dockercodeceptionrun_nginx_1 ... done
Stopping dockercodeceptionrun_php_1 ... done
Stopping dockercodeceptionrun_browser_1 ... done
Stopping dockercodeceptionrun_db_1 ... done
Removing dockercodeceptionrun_codecept_1 ... done
Removing dockercodeceptionrun_nginx_1 ... done
Removing dockercodeceptionrun_php_1 ... done
Removing dockercodeceptionrun_browser_1 ... done
Removing dockercodeceptionrun_db_1 ... done
Removing network dockercodeceptionrun_default
dev@dev-Aspire-V3-772:~$ docker-compose -f ~/projects/docker-yii2-app-advanced/docker-codeception-run/docker-compose.yml up -d
Creating network "dockercodeceptionrun_default" with the default driver
Creating dockercodeceptionrun_db_1
Creating dockercodeceptionrun_browser_1
Creating dockercodeceptionrun_php_1
Creating dockercodeceptionrun_nginx_1
Creating dockercodeceptionrun_codecept_1
dev@dev-Aspire-V3-772:~$ curl -L https://github.com/docker/compose/releases/download/1.15.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   617    0   617    0     0    799      0 --:--:-- --:--:-- --:--:--   798
100 8650k  100 8650k    0     0  1757k      0  0:00:04  0:00:04 --:--:-- 2261k
dev@dev-Aspire-V3-772:~$ chmod +x /usr/local/bin/docker-compose
dev@dev-Aspire-V3-772:~$ docker-compose -f ~/projects/docker-yii2-app-advanced/docker-codeception-run/docker-compose.yml down
Stopping dockercodeceptionrun_nginx_1   ... done
Stopping dockercodeceptionrun_php_1     ... done
Stopping dockercodeceptionrun_browser_1 ... done
Stopping dockercodeceptionrun_db_1      ... done
Removing dockercodeceptionrun_codecept_1 ... done
Removing dockercodeceptionrun_nginx_1    ... done
Removing dockercodeceptionrun_php_1      ... done
Removing dockercodeceptionrun_browser_1  ... done
Removing dockercodeceptionrun_db_1       ... done
Removing network dockercodeceptionrun_default
dev@dev-Aspire-V3-772:~$ docker-compose -f ~/projects/docker-yii2-app-advanced/docker-codeception-run/docker-compose.yml up -d
Creating network "dockercodeceptionrun_default" with the default driver
Creating dockercodeceptionrun_db_1 ... 
Creating dockercodeceptionrun_browser_1 ... 
Creating dockercodeceptionrun_db_1
Creating dockercodeceptionrun_db_1 ... done
Creating dockercodeceptionrun_php_1 ... 
Creating dockercodeceptionrun_php_1 ... done
Creating dockercodeceptionrun_nginx_1 ... 
Creating dockercodeceptionrun_nginx_1 ... done
Creating dockercodeceptionrun_codecept_1 ... 
Creating dockercodeceptionrun_codecept_1 ... done
dev@dev-Aspire-V3-772:~$ docker-compose -f ~/projects/docker-yii2-app-advanced/docker-codeception-run/docker-compose.yml down
Stopping dockercodeceptionrun_nginx_1   ... done
Stopping dockercodeceptionrun_php_1     ... done
Stopping dockercodeceptionrun_browser_1 ... done
Stopping dockercodeceptionrun_db_1      ... done
Removing dockercodeceptionrun_codecept_1 ... done
Removing dockercodeceptionrun_nginx_1    ... done
Removing dockercodeceptionrun_php_1      ... done
Removing dockercodeceptionrun_browser_1  ... done
Removing dockercodeceptionrun_db_1       ... done
Removing network dockercodeceptionrun_default
dev@dev-Aspire-V3-772:~$ docker-compose -f ~/projects/docker-yii2-app-advanced/docker-codeception-run/docker-compose.yml up -d
Creating network "dockercodeceptionrun_default" with the default driver
Creating dockercodeceptionrun_db_1 ... 
Creating dockercodeceptionrun_browser_1 ... 
Creating dockercodeceptionrun_db_1
Creating dockercodeceptionrun_db_1 ... done
Creating dockercodeceptionrun_php_1 ... 
Creating dockercodeceptionrun_php_1 ... done
Creating dockercodeceptionrun_nginx_1 ... 
Creating dockercodeceptionrun_nginx_1 ... done
Creating dockercodeceptionrun_codecept_1 ... 
Creating dockercodeceptionrun_codecept_1 ... done
dev@dev-Aspire-V3-772:~$ curl -L https://github.com/docker/compose/releases/download/1.17.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   617    0   617    0     0    665      0 --:--:-- --:--:-- --:--:--   664
100 8649k  100 8649k    0     0  2010k      0  0:00:04  0:00:04 --:--:-- 2705k
dev@dev-Aspire-V3-772:~$ chmod +x /usr/local/bin/docker-compose
dev@dev-Aspire-V3-772:~$ docker-compose -f ~/projects/docker-yii2-app-advanced/docker-codeception-run/docker-compose.yml down
Stopping dockercodeceptionrun_nginx_1   ... done
Stopping dockercodeceptionrun_php_1     ... done
Stopping dockercodeceptionrun_browser_1 ... done
Stopping dockercodeceptionrun_db_1      ... done
Removing dockercodeceptionrun_codecept_1 ... done
Removing dockercodeceptionrun_nginx_1    ... done
Removing dockercodeceptionrun_php_1      ... done
Removing dockercodeceptionrun_browser_1  ... done
Removing dockercodeceptionrun_db_1       ... done
Removing network dockercodeceptionrun_default
dev@dev-Aspire-V3-772:~$ docker-compose -f ~/projects/docker-yii2-app-advanced/docker-codeception-run/docker-compose.yml up -d
Creating network "dockercodeceptionrun_default" with the default driver
Creating dockercodeceptionrun_browser_1 ... 
Creating dockercodeceptionrun_db_1 ... 
Creating dockercodeceptionrun_db_1
Creating dockercodeceptionrun_db_1 ... done
Creating dockercodeceptionrun_php_1 ... 
Creating dockercodeceptionrun_php_1 ... done
Creating dockercodeceptionrun_nginx_1 ... 
Creating dockercodeceptionrun_nginx_1 ... done
Creating dockercodeceptionrun_codecept_1 ... 
Creating dockercodeceptionrun_codecept_1 ... done
dev@dev-Aspire-V3-772:~$ curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   617    0   617    0     0    793      0 --:--:-- --:--:-- --:--:--   793
100 8280k  100 8280k    0     0  1619k      0  0:00:05  0:00:05 --:--:-- 2225k
dev@dev-Aspire-V3-772:~$ chmod +x /usr/local/bin/docker-compose
dev@dev-Aspire-V3-772:~$ docker-compose -f ~/projects/docker-yii2-app-advanced/docker-codeception-run/docker-compose.yml down
Stopping dockercodeceptionrun_nginx_1   ... done
Stopping dockercodeceptionrun_php_1     ... done
Stopping dockercodeceptionrun_browser_1 ... done
Stopping dockercodeceptionrun_db_1      ... done
Removing dockercodeceptionrun_codecept_1 ... done
Removing dockercodeceptionrun_nginx_1    ... done
Removing dockercodeceptionrun_php_1      ... done
Removing dockercodeceptionrun_browser_1  ... done
Removing dockercodeceptionrun_db_1       ... done
Creating dockercodeceptionrun_db_1       ... done
dev@dev-Aspire-V3-772:~$ docker-compose -f ~/projects/docker-yii2-app-advanced/docker-codeception-run/docker-compose.yml up -d
Creating dockercodeceptionrun_php_1      ... done
Creating dockercodeceptionrun_browser_1  ... 
Creating dockercodeceptionrun_nginx_1    ... done
Creating dockercodeceptionrun_browser_1  ... done
Creating dockercodeceptionrun_nginx_1    ... 
Creating dockercodeceptionrun_codecept_1 ... done
```

**Comment by bscheshirwork** [comment]
upd: `1.17.1` < `eater` < `1.18.0-rc1`
```sh
dev@dev-Aspire-V3-772:~$ curl -L https://github.com/docker/compose/releases/download/1.17.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   617    0   617    0     0    801      0 --:--:-- --:--:-- --:--:--   801
100 8649k  100 8649k    0     0  1907k      0  0:00:04  0:00:04 --:--:-- 2751k
dev@dev-Aspire-V3-772:~$ chmod +x /usr/local/bin/docker-compose
dev@dev-Aspire-V3-772:~$ docker-compose -f ~/projects/docker-yii2-app-advanced/docker-codeception-run/docker-compose.yml down
Stopping dockercodeceptionrun_nginx_1   ... done
Stopping dockercodeceptionrun_php_1     ... done
Stopping dockercodeceptionrun_browser_1 ... done
Stopping dockercodeceptionrun_db_1      ... done
Removing dockercodeceptionrun_codecept_1 ... done
Removing dockercodeceptionrun_nginx_1    ... done
Removing dockercodeceptionrun_php_1      ... done
Removing dockercodeceptionrun_browser_1  ... done
Removing dockercodeceptionrun_db_1       ... done
Removing network dockercodeceptionrun_default
dev@dev-Aspire-V3-772:~$ docker-compose -f ~/projects/docker-yii2-app-advanced/docker-codeception-run/docker-compose.yml up -d
Creating network "dockercodeceptionrun_default" with the default driver
Creating dockercodeceptionrun_browser_1 ... 
Creating dockercodeceptionrun_db_1 ... 
Creating dockercodeceptionrun_db_1
Creating dockercodeceptionrun_db_1 ... done
Creating dockercodeceptionrun_php_1 ... 
Creating dockercodeceptionrun_php_1 ... done
Creating dockercodeceptionrun_nginx_1 ... 
Creating dockercodeceptionrun_nginx_1 ... done
Creating dockercodeceptionrun_codecept_1 ... 
Creating dockercodeceptionrun_codecept_1 ... done
dev@dev-Aspire-V3-772:~$ curl -L https://github.com/docker/compose/releases/download/1.18.0-rc1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   617    0   617    0     0    819      0 --:--:-- --:--:-- --:--:--   819
100 8280k  100 8280k    0     0  2022k      0  0:00:04  0:00:04 --:--:-- 3027k
dev@dev-Aspire-V3-772:~$ chmod +x /usr/local/bin/docker-compose
dev@dev-Aspire-V3-772:~$ docker-compose -f ~/projects/docker-yii2-app-advanced/docker-codeception-run/docker-compose.yml down
Stopping dockercodeceptionrun_nginx_1   ... done
Stopping dockercodeceptionrun_php_1     ... done
Stopping dockercodeceptionrun_browser_1 ... done
Stopping dockercodeceptionrun_db_1      ... done
Removing dockercodeceptionrun_codecept_1 ... done
Removing dockercodeceptionrun_nginx_1    ... done
Removing dockercodeceptionrun_php_1      ... done
Removing dockercodeceptionrun_browser_1  ... done
Removing dockercodeceptionrun_db_1       ... done
Creating dockercodeceptionrun_db_1       ... done
dev@dev-Aspire-V3-772:~$ docker-compose -f ~/projects/docker-yii2-app-advanced/docker-codeception-run/docker-compose.yml up -d
Creating dockercodeceptionrun_php_1      ... done
Creating dockercodeceptionrun_browser_1  ... 
Creating dockercodeceptionrun_nginx_1    ... done
Creating dockercodeceptionrun_php_1      ... 
Creating dockercodeceptionrun_nginx_1    ... 
Creating dockercodeceptionrun_codecept_1 ... done
```

**Comment by bscheshirwork** [comment]
https://github.com/docker/compose/compare/1.17.1...1.18.0-rc1

**Comment by bscheshirwork** [comment]
I think this lines is a source of error (list of parent incorrect)
https://github.com/docker/compose/commit/6dfd4693548520b3ca4d1fb284984d9781433fc5#diff-cc0bdcabec52683536cc42d4d0e7ac49R40

**Comment by bscheshirwork** [comment]
#5689

**Comment by ofek** [comment]
@shin- Any progress on this?

**Comment by shin-** [comment]
Fixed in #5735

**Comment by bscheshirwork** [comment]
I try it now with fresh tag (I can see fix in commits list https://github.com/docker/compose/compare/1.20.0-rc1...master)

Error still alive. 
![peek 2018-03-05 14-20](https://user-images.githubusercontent.com/5769211/36972682-15873250-2081-11e8-9720-c395fb0015f6.gif)

**Comment by bscheshirwork** [comment]
@shin- @mnottale

**Comment by bscheshirwork** [comment]
I can see some like array indexed by service names (with count of copy) 
`scale = scale_override[service.name]`

this array all times is equals to self (first time - print "..."; second time - print "done")?

**Comment by bscheshirwork** [comment]
https://github.com/docker/compose/pull/5735#issuecomment-370390948

**Comment by mnottale** [comment]
Ok I figured out what's going wrong thanks to your sample compose file. Fix is underway.

**Comment by ofek** [comment]
@mnottale What is the issue?

**Comment by mnottale** [comment]
The current code assumes that all log lines are displayed when computing the offset to move to, but this is not the case when there are dependencies between services.

**Comment by lougaou** [comment]
+1
