### ISSUE TITLE
insecure mode isn't enabled.

### ISSUE THREAD

**Issue by sirwolfgang** [docker/compose#563]
With version `1.0.0` I now get the `docker.errors.DockerException: HTTPS endpoint unresponsive and insecure mode isn't enabled.` when connecting to my private `http` repo. I do not see a way to allow/change the behavior to use `http`.

**Comment by mouadino** [comment]
@dnephin I think there were a typo on your command it should be: ``fig pull --allow-insecure-ssl`` and not ``docker ...``.

Cheers,

**Comment by sirwolfgang** [comment]
@mouadino he was speaking to the work around until that patch was pushed. But thanks!

**Comment by wangzi19870227** [comment]
I got same problem (I'm on docker 1.5.0 and fig 1.1.0). 

```
[root@haichuan-vm fig-elk]# docker-compose pull
Pulling elasticsearch (registry.docker.sce.sina.com/deviantony/elk-elasticsearch:latest)...
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 31, in main
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 27, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 59, in perform_command
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 231, in pull
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.project", line 197, in pull
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 523, in pull
  File "/code/build/docker-compose/out00-PYZ.pyz/docker.client", line 824, in pull
  File "/code/build/docker-compose/out00-PYZ.pyz/docker.auth.auth", line 67, in resolve_repository_name
  File "/code/build/docker-compose/out00-PYZ.pyz/docker.auth.auth", line 46, in expand_registry_url
docker.errors.DockerException: HTTPS endpoint unresponsive and insecure mode isn't enabled.
```

following cmd work for me:
```docker-compose up --allow-insecure-ssl```

**Comment by yoanisgil** [comment]
Same issue here. I ran  docker-compose up  and got:

``` 
Recreating root_zabbix_1...
Creating root_influxdb_1...
Pulling image docker.io/tutum/influxdb:latest...
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 31, in main
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 27, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 59, in perform_command
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 464, in up
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.project", line 208, in up
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 214, in recreate_containers
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 197, in create_container
  File "/code/build/docker-compose/out00-PYZ.pyz/docker.client", line 710, in pull
  File "/code/build/docker-compose/out00-PYZ.pyz/docker.auth.auth", line 67, in resolve_repository_name
  File "/code/build/docker-compose/out00-PYZ.pyz/docker.auth.auth", line 46, in expand_registry_url
docker.errors.DockerException: HTTPS endpoint unresponsive and insecure mode isn't enabled.
```

However this command did work (notice I did not need to pass --allow-insecure-ssl):

```
docker pull docker.io/tutum/influxdb:latest
``` 

I'm running docker 1.6.0 On CentOS7.:

```
[root@aws034 ~]# docker -v
Docker version 1.6.0, build 8aae715/1.6.0
```

**Comment by whitney-beck** [comment]
I'm experiencing the same thing as @yoanisgil. `--insecure-registry` is configured in the docker daemon.

**Comment by whitney-beck** [comment]
I'm experiencing the same thing as @yoanisgil. `--insecure-registry` is configured in the docker daemon.

**Comment by smboykin** [comment]
I'm also experiencing the same as @whitney-beck and @yoanisgil, I'm trying to pull from a private registry.  `docker pull` works, but `docker-compose up` does not

**Comment by aanand** [comment]
Fixed by #1736 and released in [Compose 1.4.0 RC2](https://github.com/docker/compose/releases/tag/1.4.0rc2).

**Comment by alexeyOnGitHub** [comment]
I tried both Compose 1.3.x and 1.4.0RC2.
it still cannot load data from private HTTPS site. if I add "--insecure-registry mysitehere", then it prints out help text and does not seem to accept the parameter.

**Comment by yoanisgil** [comment]
@alexeyOnGitHub can you share your docker version as well as the traceback? That might help others to help you figuring out what the issue is ;) or even try to reproduce the problem.

**Comment by alexeyOnGitHub** [comment]
@yoanisgil , thank you for getting back to me. I'm sorry, I was in a hurry and didn't provide more details hoping that maybe it was a known issue already.
here is the output: https://gist.github.com/alexeyOnGitHub/7903076e81fd9aedda96

this is on MacOS 10.

**Comment by yoanisgil** [comment]
@alexeyOnGitHub I don't think this ticket refers to the same issue you're facing. Actually if you take a look at  `docker-compose up --help` and you will see there is no such option ` --insecure-registry` for the up command, which is why you get the command's documentation. I believe that's a setting you will when launching the daemon. Also make sure you run `docker login` before asking compose to launch your services.

**Comment by alexeyOnGitHub** [comment]
alright, thank you. that parameter was printed out as a suggestion when I ran "docker-compose up -d":
it said 
503 cannot connect to something-something-self-signed certificate, 
please use this parameter. --insecure-registry mysite

and then the parameter was ignored when I provided it...

**Comment by aanand** [comment]
@alexeyOnGitHub Rather confusingly, that error is actually coming from the Docker daemon: wherever `docker -d` is running (your laptop, a VM, a cloud server), you need to add `--insecure-registry HOST:PORT` to the command when starting it up.

**Comment by alexeyOnGitHub** [comment]
alright, I see. thank you, I will look into this

**Comment by roblayton** [comment]
Have any of these solutions worked for anyone?

**Comment by bheesham** [comment]
Not for me, no.

<img width="1222" alt="screen shot 2016-10-04 at 8 50 28 pm" src="https://cloud.githubusercontent.com/assets/171007/19097651/47af8150-8a74-11e6-9ebc-08eb26535249.png">

The registry is for sure running on port 5000.
