### ISSUE TITLE
"Can't find a suitable configuration file" on Ubuntu 18.04.1

### ISSUE THREAD

**Issue by boldt** [docker/compose#6361]
I am running a fresh Ubuntu 18.04:

```
$ cat /etc/issue
Ubuntu 18.04.1 LTS \n \l
```

I added the APT apt-repositries [as described here](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-18-04). I have docker 18.09.0 and docker-compose 1.22.0:

```
root@srv:/docker# docker version
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:49:01 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false
root@srv:/docker# docker-compose version
docker-compose version 1.22.0, build unknown
docker-py version: 3.5.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
root@srv:/docker#
```
I want to use docker-compose in a folder called `/docker`:

```
root@srv:/docker# ls -l
total 4
-rwxr-xr-x 1 administrator docker 458 Nov 22 13:44 docker-compose.yml
```

If I hit `docker-compose up`, I get the following error:

```
ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml
```

Any idea? How can I debug that issue?

**Comment by boldt** [comment]
My workaround:

I assume, docker-compose was installed automatically, when I installed the docker-ce package. Since [I wasn't able to stop containers, I disabled Appmour](https://forums.docker.com/t/can-not-stop-docker-container-permission-denied-error/41142/6). It seems, that this removed docker-compose as well. Thus, I [installed docker-compose](https://www.digitalocean.com/community/tutorials/how-to-install-docker-compose-on-ubuntu-18-04) manually. Now, docker-compose works for me.

**Comment by shin-** [comment]
The original issue was probably a permissions problem, but I'm glad you could solve it regardless.

**Comment by boldt** [comment]
Since I am not the only one, I'll try to create a MWE.

@xy2z I assume, you just overwrote the docker-compose Binary, which was installed by docker.

**Comment by prvak** [comment]
> I ran into the same problem with a fresh Ubuntu 18.04 install, where I selected Docker from install options.
I had the exactly same issue. After some digging I found out that the docker-compose was installed as a "snap" package. Applications from snap packages are running in a sandbox and they do not see the /tmp directory where I happened to have my `docker-compose.yml` file. Solution:
```
sudo snap remove docker
sudo apt install docker.io docker-compose
```

**Comment by pream-totaram** [comment]
I also had issues with apt's `docker-compose`

[This documentation from docker worked well for me.](https://docs.docker.com/compose/install/)

**Comment by chuongtrh** [comment]
Same issue. Any solution to fix it? Thanks

```
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
```

**Comment by nxasana** [comment]
You need to run your command in the same folder as your doocker-compose.yml file

**Comment by austenwho** [comment]
@prvak's solution worked for me. Muchas gracias!

**Comment by caugner** [comment]
I ran into the same issue and found an explanation in the [docker/docker-snap README](https://github.com/docker/docker-snap#usage):

> All files that docker needs access to should live within your `$HOME` folder.

If the `docker-compose.yml` is outside of the `$HOME` folder, `docker-snap` won't see it.

**Solution**: Move the `docker-compose.yml` inside your `$HOME` directory.

**Comment by ashwanijha04** [comment]
You might want to use:

----
**docker-compose up -f <path_to_file> to specify the correct path**
----

**Comment by SigiSang** [comment]
> > I ran into the same problem with a fresh Ubuntu 18.04 install, where I selected Docker from install options.
> 
> I had the exactly same issue. After some digging I found out that the docker-compose was installed as a "snap" package. Applications from snap packages are running in a sandbox and they do not see the /tmp directory where I happened to have my `docker-compose.yml` file. Solution:
> 
> ```
> sudo snap remove docker
> sudo apt install docker.io docker-compose
> ```
I had the same issue as well (Ubuntu fresh install + selected docker during installation). However, executing the above commands didn't quite fix it, I got this error:
```
-bash: /snap/bin/docker-compose: No such file or directory
```
 I downloaded the binary (per instructions from the [documentation](https://docs.docker.com/compose/install/)) and had to remove the old snap script:
```
sudo curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
sudo rm /usr/bin/docker-compose
```

**Comment by artem-shestakov** [comment]
Ran command and get error:

~$ docker-compose ps
ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml

but --version work correct,
~$ docker-compose --version
docker-compose version 1.25.5, build 8a1c60f6

**Comment by caugner** [comment]
> ~$ docker-compose ps

There is no `docker-compose.yml` in your home directory. Please `cd` into the directory with that file first.

**Comment by caugner** [comment]
> ~$ docker-compose ps

There is no `docker-compose.yml` in your home directory. Please `cd` into the directory with that file first.

**Comment by slimcdk** [comment]
Same issue on fresh install with Ubuntu Server 20.04.1 LTS. Also selected docker from the recommended packages during install.

```
ubuntu@main:/auto$ ll
total 48
drwxr-xr-x  6 ubuntu ubuntu 4096 Jul 29 16:54 ./
drwxr-xr-x 21 root   root   4096 Jul 29 16:24 ../
drwxrwxr-x  9 ubuntu ubuntu 4096 Jul 29 16:40 .git/
-rw-rw-r--  1 ubuntu ubuntu   59 Jul 29 16:24 .gitattributes
-rw-rw-r--  1 ubuntu ubuntu    8 Jul 29 16:46 .gitignore
-rw-rw-r--  1 ubuntu ubuntu   83 Jul 29 16:24 .gitmodules
-rw-rw-r--  1 ubuntu ubuntu  819 Jul 29 16:24 README.md
-rw-rw-r--  1 ubuntu ubuntu 6913 Jul 29 16:43 docker-compose.yaml
drwxrwxr-x  2 ubuntu ubuntu 4096 Jul 29 16:24 media/
drwxrwxr-x  2 ubuntu ubuntu 4096 Jul 29 16:40 secrets/
drwxrwxr-x 14 ubuntu ubuntu 4096 Jul 29 16:39 services/
ubuntu@main:/auto$ docker-compose pull
ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml
        
ubuntu@main:/auto$ 
```

**Comment by seekwhencer** [comment]
yes. the same on on a fresh ubuntu 20.

**Comment by alexhe** [comment]
sudo -i  helped me

**Comment by seekwhencer** [comment]
Installed manually... that works.

**Comment by emexelem** [comment]
Same issue as well on a fresh Ubuntu 20.04. Solved by `sudo snap remove docker && sudo apt install docker.io docker-compose` as mentioned by prvak.
This difference between the behavior of snap and apt packages is really misleading.

**Comment by NemanjaMucalovic** [comment]
Same problem,but prvak solution didn't work for me (docker was never installed using snap).
OS Version:Ubuntu 20.04
Python 3.8.5
Docker version 19.03.8
docker-compose version 1.25.0

**Comment by duel007** [comment]
Same problem on a fresh install. Not fixed.

`root@srv:/srv/docker/plex# ls
docker-compose.yaml  docker-compose.yml
root@srv:/srv/docker/plex# docker-compose up
ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml

root@srv:/srv/docker/plex#
`

**Comment by viniciusclerod** [comment]
same problem

**Comment by duel007** [comment]
@shin- Can this be re opened?

**Comment by atul-gautam-au6** [comment]
i have getting same problem 



$ make start
Pulling postgres      ... done
Pulling hydra-migrate ... done
Pulling hydra         ... done
Recreating reaction-hydra_postgres_1 ... done
Recreating reaction-hydra_hydra-migrate_1 ... done
Recreating reaction-hydra_hydra_1         ... done
Pulling mongo ... done
Pulling api   ... done
Recreating reaction_mongo_1 ... done
Recreating reaction_api_1   ... done
Pulling identity ... done
Recreating reaction-identity_identity_1 ... done
/bin/sh: 1: cd: can't cd to reaction-admin
ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml
        
make: *** [Makefile:348: start-reaction-admin] Error 1

**Comment by sakeeljawfer** [comment]
save as ->>>>    docker-compose.yaml  --not iml

**Comment by nicbou** [comment]
(this is just a recap for people landing here from Google)

## Symptoms

When you run `docker-compose up` or `docker-compose build`, you get this message:

```
ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml
```

If you run `docker-compose --version`, you get something like this:

```
docker-compose version 1.25.5, build unknown
```

## Cause

This issue happens with Ubuntu's default docker installation (when you check the "docker" option during the Ubuntu installation). It happens in Ubuntu 20.04 and 21.04, and possibly in other versions.

## Fix

1. Uninstall the current docker version, and install the correct version
    ```
    sudo snap remove docker
    ```
2. Install the correct docker-compose version by following the [official instructions](https://docs.docker.com/compose/install/#install-compose).
3. Run `docker-compose`. If you get `/snap/bin/docker-compose: No such file or directory`, just start a new shell (or type `bash`).
 
`docker-compose --version` should now give you the correct version, with the correct build number, and run properly.

**Comment by buiquangquyet** [comment]
you need save as file docker-compose.yml to docker-compose.yaml

**Comment by marchrius** [comment]
Same problem on macOS.
After upgradint Docker Desktop to latest version

> Version **3.4.0 (65384)**
> Engine **20.10.7**
> Compose **2.0.0-beta.3**
> Credential Helper **0.6.4**
> Kubernetes **v1.21.1**
> Snyk **v1.563.0**

The **/user/local/bin/docker-compose** was overriden by docker.
To solve this I've re-installed **brew reinstall docker-compose** (to install **brew install docker-compose**)

**Comment by paradoxministry** [comment]
I reproduced this problem on OSX Big Sur 11.4 with Docker for Mac 3.5.2.

Re-installing `docker-compose` with brew did NOT work for me. What did work was disabling `Docker Compose v2` in my Docker for Mac preferences:
![image](https://user-images.githubusercontent.com/326654/127094480-3faaf8e0-ece0-4109-a747-afb3317487fc.png)

**Comment by alan345** [comment]
I had a space int he end of my file `docker-compose.yml `
That was the issue for me.. :/

**Comment by Targetarm-Ankit** [comment]
Hello, I got the same error. I reinstall the docker and also run the command in the directory with .yml file.

**Comment by soiqualang** [comment]
> > I ran into the same problem with a fresh Ubuntu 18.04 install, where I selected Docker from install options.
> 
> I had the exactly same issue. After some digging I found out that the docker-compose was installed as a "snap" package. Applications from snap packages are running in a sandbox and they do not see the /tmp directory where I happened to have my `docker-compose.yml` file. Solution:
> 
> ```
> sudo snap remove docker
> sudo apt install docker.io docker-compose
> ```

Great!, that solve my problem

**Comment by richard015ar** [comment]
[This](https://github.com/docker/compose/issues/6361#issuecomment-887194948) worked on Mac (M1)

Thanks @paradoxministry !

**Comment by shreekrishnaacharya** [comment]
I am having same issue. docker-compose works on one project but no other project. I tried creating new docker-compose.yml file update and all other stuff but none worked for me. My current docker version is:
Client:
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.17.3
 Git commit:        20.10.12-0ubuntu4
 Built:             Mon Mar  7 17:10:06 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       a89b842
  Built:            Thu Sep 22 06:22:13 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0


and none of above solution worked for me.
