### ISSUE TITLE
Circular import between container1 and container2

### ISSUE THREAD

**Issue by jmreicha** [docker/compose#666]
I am hitting an issue where I need 2 containers to be able to communicate with each other, ie one container needs to be able to ping the other and vice versa but when I add each container in to the links section of the fig.yml file I get a `Circular import between container1 and container2` error when I run fig up.

Is there a workaround for this?  Isn't the link section just adding an entry in each containers host file?  If so, shouldn't that be allowed for containers to be able to communicate with each other?

Here is the bit causing problems.  Obviously I have changed some of the names around.

```
container1:
  image: user/container1
  ports:
    - "8000:8000"
  links:
    - "container2:container2"

container2:
  image: user/container2
  ports:
    - "8080:8080"
  links:
    - "container1:container1"
```

Is there something I am missing here?

**Comment by mucsi96** [comment]
You can create bidirectional links using a custom tiny DNS server. So instead of this

    serviceb:
        image: username/serviceb

    servicea:
        image: username/servicea
        links:
            - serviceb

Try this

    dnsdock:
        image: tonistiigi/dnsdock
        volumes:
            - /var/run/docker.sock:/run/docker.sock
        ports:
            - 172.17.42.1:53:53/udp
    serviceb:
        image: username/serviceb
        dns: 172.17.42.1

    servicea:
        image: username/servicea
        dns: 172.17.42.1

You can access the services with: `<container-name>.<image-name>.docker` hostname.
You can check `<container-name>` and `<image-name>` after `docker-compose up` in dnsdock logs.

**Comment by dnephin** [comment]
This is being addressed in #1676

**Comment by dpwspoon** [comment]
Sorry, late to the party.  @dnephin, I still get circular dependency error in 1.9.0.  Having read #1676 and network docs I don't yet have a suitable solution with out using work around listed above.  Use case is two containers that load balance and cluster to each other. 

Simplified yml
```
gateway-member1:
  image: gateway.ex.base
  links:
    - gateway-member2:clueter.member.com
  hostname: gateway.example.com
  command: gateway.start --config conf/gateway-cluster-config.xml
gateway-member2:
  image: gateway.ex.base
  links:
    - gateway-member1:clueter.member.com
  hostname: gateway.example.com
  command: gateway.start --config conf/gateway-cluster-config.xml
 
```

my versions
```
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by dnephin** [comment]
Are you using the `--x-networking` flag to `docker-compose` ?  Can you include the command you are running and the output ?

**Comment by dpwspoon** [comment]
Thanks @dnephin, its working with the networking commands now!  I was missing the flag.  One question.  Our application has a quirk for binding on clustering it assumes you know the interface name for the configuration (inherited by old hazelcast libraries).  We are working on a patch on our end to configure it via domain names.  In the mean time can we count on the interface names that the container sees as being deterministic?

```
docker-compose --x-networking -f jms.cluster.yml up
WARNING: 
Some services ("gateway-member1", "gateway-member2") define links, which are not compatible with Docker networking and will be ignored.
Future versions of Docker will not support links - you should remove them for forwards-compatibility.
```

**Comment by dnephin** [comment]
I'm not sure about that. From what I've seen it's always `eth0`, but I'm not sure that's a guarantee. There might be something about it in the docker networking docs.

**Comment by zx1986** [comment]
this issue is evil ...

**Comment by ei-grad** [comment]
Sad.

**Comment by abdoulsn** [comment]
Hit this also.
