### ISSUE TITLE
OpenSSL version mismatch. Built against 1010106f, you have 101000cf

### ISSUE THREAD

**Issue by Legion2** [docker/compose#7686]
## Description of the issue

Error when using `docker-compose exec` with `DOCKER_HOST=ssh://...`

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.26.2, build eefe0d31
docker-py version: 4.2.2
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:49:27 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
```
version: '3'

services:
  portainer:
    image: portainer/portainer:1.24.1
    command: -H unix:///var/run/docker.sock
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  data:

```

## Steps to reproduce the issue

1. create a `.env` file and add `DOCKER_HOST=ssh://...` with a valid ssh host with docker engine
2. `docker-compose up -d`
3. `docker-compose exec portainer bash`

### Observed result
```
error during connect: Get http://docker/v1.40/containers/a1a823ab0e6b66087bf0fd609c34da5e70c23446cf19791f66d6bf277f14f89a/json: command [ssh -- example.org docker system dial-stdio] has exited with exit status 255, please make sure the URL is valid, and Docker 18.09 or later 
is installed on the remote host: stderr=OpenSSL version mismatch. Built against 1010106f, you have 101000cf
```
### Expected result

Open a bash terminal in the `portainer` container on the remote docker engine.

### Stacktrace / full error message

```
error during connect: Get http://docker/v1.40/containers/a1a823ab0e6b66087bf0fd609c34da5e70c23446cf19791f66d6bf277f14f89a/json: command [ssh -- example.org docker system dial-stdio] has exited with exit status 255, please make sure the URL is valid, and Docker 18.09 or later 
is installed on the remote host: stderr=OpenSSL version mismatch. Built against 1010106f, you have 101000cf
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.
Running on WSL 2 Ubuntu on windows 10. The docker-compose is the one mounted from docker desktop.
But I also tested with a native linux machine.

I tested with two remote hosts, one google vm and one raspberry pi.
On the google vm:
```
Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.13.5
 Git commit:        369ce74
 Built:             Tue May 19 10:01:57 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.5
  Git commit:       369ce74
  Built:            Tue May 19 10:00:30 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.2
  GitCommit:        ff48f57fc83a8c44cf4ad5d672424a98ba37ded6
 runc:
  Version:          1.0.0-rc10
  GitCommit:
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683b971d9c3ef73f284f176672c44b448662
```

On the raspberrypi:
```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a6621
 Built:             Mon Jun 22 15:53:41 2020
 OS/Arch:           linux/arm
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a6621
  Built:            Mon Jun 22 15:47:34 2020
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
I also tested with older docker compose version 1.25.5 and the newer 1.27.0-rc1.

**Comment by zorion79** [comment]
I can run
```
docker-compose -H ssh://user@machine up
docker-compose -H ssh://user@machine build
docker -H ssh://user@machine up image prune -f
```
but this return error.
```
docker-compose -H ssh://user@machine run esb-kav
Creating esb-kav_esb-kav_run ... done
error during connect: Get http://docker/v1.40/containers/3c6e7690875470e51e1eca48100933e87a9aca25c298a70d5b48e09f33bd3de7/json: command [ssh -l user -- machine docker system dial-stdio] has exited with exit status 255, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=OpenSSL version mismatch. Built against 1010106f, you have 101000cf
```
All version docker 19.03.12, docker-compose 1.27.2, openssl 1.1.1f - equals.

**Comment by qalex** [comment]
I'm having the same issue. Guess this is because docker-compose is built against OpenSSL 1.1.0l:
```
$ docker-compose version 
docker-compose version 1.27.2, build 18f557f9
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Comment by mnowaczyk** [comment]
As a workaround you can install docker-compose from PIP.

**Comment by al-cheb** [comment]
I can reproduce the same behavior on Ubuntu 20.04:

#### OS Version
```
# lsb_release -a
No LSB modules are available.
Distributor ID:Ubuntu
Description:Ubuntu 20.04.2 LTS
Release:20.04
Codename:focal
```

#### Output of docker-compose version
```
# docker-compose version
docker-compose version 1.28.2, build 67630359
docker-py version: 4.4.1
CPython version: 3.7.9
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```
#### Result
```
# docker-compose -H ssh://user@machine up
OpenSSL version mismatch. Built against 1010106f, you have 101000cf
```

Any chance @chris-crone to fix the issue?

**Comment by adamburgess** [comment]
Happened to me to on 20.04.
Using 1.28.0 works fine for me, though curiously it seems to be using a more recent version of openssl compared to 1.28.2?

```
$ docker-compose version
docker-compose version 1.28.0, build d02a7b1a
docker-py version: 4.4.1
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

**Comment by laszukdawid** [comment]
Can confirm that had the exact same issue with `1.28.2` but `1.28.0` worked fine. Downloaded releases directly from github.

```
$ openssl version
OpenSSL 1.1.1f  31 Mar 2020
$ uname -a
Linux junk 5.8.0-43-generic #49~20.04.1-Ubuntu SMP Fri Feb 5 09:57:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by lucas42** [comment]
For anyone looking for a workaround, I've found adding `COMPOSE_PARAMIKO_SSH=1` avoids the error in my environment.
Don't think that flag appears in the docs, but it was suggested to me as a workaround for another issue, so I thought I'd try it here too and it helped!

**Comment by HeCorr** [comment]
same on Ubuntu 20 WSL.

Docker version 20.10.3
docker-compose version 1.28.4

downgrading to compose v1.28.0 did not solve the issue.

trying to run on a Linux server through SSH (`docker context`)

**Comment by nthuemmel** [comment]
docker-compose 1.28.5 does not fix the issue for me.

I'm still getting

```
error during connect: Get http://docker/v1.24/containers/<id>/json: command [ssh -l ci -- <address> docker system dial-stdio] has exited with exit status 255, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=OpenSSL version mismatch. Built against 1010106f, you have 101000cf
```

**Local host:**
* Ubuntu 20.04
* docker-compose version 1.28.5, build c4eb3a1f
* Docker version 20.10.3, build 48d30b5

**Remote host:**
* Ubuntu 18.04
* Docker version 20.10.5, build 55c4c88

With docker-compose version 1.28.0 it works!

**Comment by zorion79** [comment]
`docker-compose --host build` started to build image locally. But now started to work docker-compose with docker context.

**Comment by NoharaMasato** [comment]
This happened on github actions.
I solved by fixing ubuntu version.
`runs-on: ubuntu-latest`  -> `runs-on: ubuntu-18.04`
ubuntu-latest version has changed 18.04 to 20.04. Along with this, docker-compose verion has been updated, and updated dokcer-compose cause this error.

**Comment by MaxDaten** [comment]
> This happened to me on `github actions`.
> I solved by fixing ubuntu version.
> `runs-on: ubuntu-latest` -> `runs-on: ubuntu-18.04`
> ubuntu-latest version has changed 18.04 to 20.04. Along with this, docker-compose verion has been updated, and updated dokcer-compose cause this error.

This worked for my manual `docker-compose` with env var DOCKER_HOST on a remote host. THX!

**Comment by Tiim** [comment]
Why is this issue closed? I have docker-compose version 1.28.5, build c4eb3a1f on Windows WSL2 and get this error now. How can I downgrade docker-compose on windows wsl2?

**Comment by nthuemmel** [comment]
@aiordache Please reopen, this issue is not fixed, neither in 1.28.5 nor 1.28.6

**Comment by satriahrh** [comment]
Still happening in `1.29.1`

**Comment by arnolanglade** [comment]
It does not work with ` 1.29.1`
```
docker-compose version    
docker-compose version 1.29.1, build c34c88b2
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```
Workaround: downgrade to 1.28.0.

**Comment by Awea** [comment]
Hi there, I got the same issue and updating to 1.29.2 solve it.

**Comment by trevordixon** [comment]
I'm seeing this using 1.29.2.

**Comment by grahamhoyes** [comment]
Still experiencing this on 1.29.2 as well.

**Local host**:
docker-compose version 1.29.2, build 5becea4
Docker version 20.10.0, build 7287ab3

**Remote host**:
Docker version 20.10.7, build f0df350 (running in Swarm mode, for what that's worth)

This is also impacting workflows in Github actions as @NoharaMasato said, which are also using v1.29.2.

**Comment by GoingTharn** [comment]
This bug still exists; I had to downgrade to 1.27.1 today after hours of failed troubleshooting

**Comment by Legion2** [comment]
@aiordache This issue still exists in docker-compose version 1.29.2, if installed from `https://github.com/docker/compose/releases/download/...`, however if installed with pip there is no error.

**Comment by lepe** [comment]
```
ocker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

Fixed this issue by using:
`docker-compose -H "ssh://user@host:port" up --build -d`

I think the use of `DOCKER_HOST` is causing the issue. In my case using `COMPOSE_PARAMIKO_SSH=1` causes another strange error.

**Comment by jamshid** [comment]
Yes! This maddening bug still exists in the 1.x binary can you download here on GitHub in releases, at least when using `DOCKER_HOST=ssh://dockerserver` on ubuntu 20.04.
`docker-compose version 1.29.2, build 5becea4c`

It causes my `docker-compose run` to fail with:
```
error during connect: Get "http://docker.example.com/v1.24/containers/271530c3abe6f8241af23845baad768f8aeb3e32d13a21733e9b18bfc5847ea3/json": command [ssh -- dockerserver docker system dial-stdio] has exited with exit status 255, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=OpenSSL version mismatch. Built against 1010106f, you have 101000cf
```

Using `"-H "ssh://host"`instead of `DOCKER_HOST=ssh://host` did **not** help.

Removing that binary from /usr/local/bin/ and doing a `pip3 install docker-compose`, as mentioned by @Legion2, does **fix** it.

The working `docker-compose --version` reports same version but unknown build:
`docker-compose version 1.29.2, build unknown`

**Comment by chris-crone** [comment]
@jamshid, are you running into issues with adopting Compose v2?
