### ISSUE TITLE
docker compose does not use current buildkit builder

### ISSUE THREAD

**Issue by strophy** [docker/compose#8531]
**Description**

`docker compose build` does not use the current buildkit builder. both `docker build` and `docker-compose build` use this builder, which I need because it contains cache mount data needed for a particularly slow `npm ci` command.

**Steps to reproduce the issue:**
1. `docker buildx create --name cacheable --use`
2. `docker buildx inspect --bootstrap`
3. `docker compose build <service_name>`

**Describe the results you received:**
The build runs and completes successfully, but does not use my currently selected builder. This can be identified by (a) the slow build and (b) if the builder is stopped beforehand with `docker stop buildx_buildkit_cacheable0` then it is still stopped after the build completes. 

**Describe the results you expected:**
I expect `docker compose build` to use my current buildkit builder, named `buildx_buildkit_cacheable0`

**Additional information you deem important (e.g. issue happens only occasionally):**
Both `docker build` and `docker-compose build` will start the currently selected builder container (if stopped) and use it to build, which leads me to believe this might be a bug in `docker compose`.

Environment contains these vars:
`COMPOSE_DOCKER_CLI_BUILD=1`
`DOCKER_BUILDKIT=1`

I have tried setting `BUILDKIT_HOST=docker-container://buildx_buildkit_cacheable0` without any change in the behaviour of `docker compose build`.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Cloud integration: 1.0.17
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:38 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:49 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
default
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.3)
  scan: Docker Scan (Docker Inc., v0.7.0)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 2
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.11.0-22-generic
 Operating System: Ubuntu 21.04
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.24GiB
 Name: W540
 ID: QNQR:7RST:WACE:AHDH:E6OR:II4B:QFD6:B7LR:K3I3:4VDE:3VPD:ZZI3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: strophy
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**
local

**Comment by rhyek** [comment]
I verified this with docker compose v2.5.0.

docker-compose.dev.yaml:
```dockerfile
version: '3'
services:
  sql-migrations:
    build:
      context: ../../..
      dockerfile: sql-migrations/Dockerfile
      cache_from:
        - type=local,src=/tmp/.buildx
      cache_to:
        - type=local,dest=/tmp/.buildx
```

```bash
❯ docker compose version
Docker Compose version v2.5.0
❯ docker buildx create --driver=docker-container --use
gracious_shaw
❯ docker compose -f docker-compose.dev.yaml build
[+] Building 0.0s (0/0)                                                                                                                                                                                                  
cache export feature is currently not supported for docker driver. Please switch to a different driver (eg. "docker buildx create --use")
```

**Comment by johanneswuerbach** [comment]
Just ran into the same issue:

compose-v2 is not picking the new buildx context and compose-v1 complains about the unknown keys:

```
The Compose file './compose.ci.yml' is invalid because:
services.service.build contains unsupported option: 'cache_to'
services.test.build contains unsupported option: 'cache_to'
```

Anyone using compose buildx cache successfully on github actions?

**Comment by johanneswuerbach** [comment]
Looks like copying the necessary logic from buildx resolves this https://github.com/docker/compose/pull/9466 🎉

**Comment by sagi-shimoni** [comment]
> I verified this with docker compose v2.5.0.
> 
> docker-compose.dev.yaml:
> 
> ```dockerfile
> version: '3'
> services:
>   sql-migrations:
>     build:
>       context: ../../..
>       dockerfile: sql-migrations/Dockerfile
>       cache_from:
>         - type=local,src=/tmp/.buildx
>       cache_to:
>         - type=local,dest=/tmp/.buildx
> ```
> 
> ```shell
> ❯ docker compose version
> Docker Compose version v2.5.0
> ❯ docker buildx create --driver=docker-container --use
> gracious_shaw
> ❯ docker compose -f docker-compose.dev.yaml build
> [+] Building 0.0s (0/0)                                                                                                                                                                                                  
> cache export feature is currently not supported for docker driver. Please switch to a different driver (eg. "docker buildx create --use")
> ```

I verified same issue with v2.5.1
Hopefully this can be resolved soon.

**Comment by blimmer** [comment]
This should still be open - it looks like it's ideally fixed by https://github.com/docker/compose/pull/9466

**Comment by fmv1992** [comment]
Plus one here.

**Comment by rbreslow** [comment]
@ndeloof Can we reopen this issue? It's still broken and would be a huge step forward, allowing folks to configure layer caching from Docker Compose.

**Comment by johanneswuerbach** [comment]
Still needed and a PR waiting for review https://github.com/docker/compose/pull/9466

**Comment by blimmer** [comment]
👍 - @nicksieger can we reopen this since https://github.com/docker/compose/pull/9466 is still pending review?

**Comment by johanneswuerbach** [comment]
The issue should be resolved in https://github.com/docker/compose/releases/tag/v2.11.0, did you test this version already?

**Comment by TafkaMax** [comment]
How can I test if this is working ?

I am trying to use gitlab-ci to build on a remote host and I want to use this feature: https://github.com/moby/buildkit/issues/978

But to use a network now with buildkit I have to specify it in the buildx create command.

So here is part of my CI.

```yaml
#.gitlab-ci.yml
 - docker context create remote_dev_server --docker "host=ssh://$DEV_SERVER_USER@$DEV_SERVER_IP"
 - docker context use remote_dev_server
- docker buildx create --name www-builder --driver docker-container --driver-opt 'network=www-test-openresty-network' --platform linux/amd64,linux/386 --use
- docker compose build
- docker compose push
```

```
 docker compose build
#1 [internal] booting buildkit
#1 starting container buildx_buildkit_www-builder0
#1 starting container buildx_buildkit_www-builder0 0.2s done
#1 ERROR: Error response from daemon: network ${NETWORK_NAME} not found
------
 > [internal] booting buildkit:
------
Error response from daemon: network ${NETWORK_NAME} not found
#1 [internal] booting buildkit
#1 CANCELED
Cleaning up project directory and file based variables 00:01
ERROR: Job failed: exit code 17
```

**Comment by TafkaMax** [comment]
```
$ docker compose build
#1 [internal] booting buildkit
#1 pulling image moby/buildkit:buildx-stable-1
#1 [internal] booting buildkit
#1 pulling image moby/buildkit:buildx-stable-1
#1 pulling image moby/buildkit:buildx-stable-1 8.8s done
#1 creating container buildx_buildkit_www-builder0 0.0s done
#1 ERROR: Error response from daemon: Conflict. The container name "/buildx_buildkit_www-builder0" is already in use by container "8791d0757fce91ae84f600df2927fae2b0033458721cbaae0823123548cfa067". You have to remove (or rename) that container to be able to reuse that name.
------
 > [internal] booting buildkit:
------
#1 pulling image moby/buildkit:buildx-stable-1 8.7s done
#1 creating container buildx_buildkit_www-builder0 0.0s done
#1 CANCELED
Error response from daemon: Conflict. The container name "/buildx_buildkit_www-builder0" is already in use by container "8791d0757fce91ae84f600df2927fae2b0033458721cbaae0823123548cfa067". You have to remove (or rename) that container to be able to reuse that name.
```

Now I am getting this.
