### ISSUE TITLE
Compose with variable on image name

### ISSUE THREAD

**Issue by cfeltz34** [docker/compose#8601]
## Context information (for bug reports)

- [X] Using Compose V2.0.0-rc.2

**Output of `docker(-)compose version`**
```
V2.0.0-rc.2
```

**Output of `docker version`**
```
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:10 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

## Steps to reproduce the issue

1. Create a yml file and define a service like (where .env file with "RABBITMQ_VERSION=3.8.9")
```
version: '3.7'
services:
  rabbitmq:
    container_name: example.rabbitmq
    image: rabbitmq:$RABBITMQ_VERSION-management

```
My container is based on image "rabbitmq:3.8.9" instead of "rabbitmq:3.8.9-management"

**Comment by cfeltz34** [comment]
No issue with docker compose 1.29.2

**Comment by ndeloof** [comment]
I just tested with rc3 and issue has been fixed it seems:
```console
$ docker compose config
services:
  rabbitmq:
    container_name: example.rabbitmq
    image: rabbitmq:3.8.9
(...)
$ rm .env 
$ docker compose config
services:
  rabbitmq:
    container_name: example.rabbitmq
    image: rabbitmq:management
(...)
$ RABBITMQ_VERSION=foo docker compose config
services:
  rabbitmq:
    container_name: example.rabbitmq
    image: rabbitmq:foo
(...)
```

**Comment by ndeloof** [comment]
Please re-open if issue persist after upgrade to v2.0.0-rc.3

**Comment by cfeltz34** [comment]
I still have the issue with rc3 but I don't know how to reopen the issue

.env

> RABBITMQ_VERSION=3.8.9

docker-compose.test.rabbitmq.yml

> version: '3.7'
> 
> services:
>   rabbitmq:
>     container_name: test.rabbitmq
>     **image: rabbitmq:$RABBITMQ_VERSION-management**
>     environment:
>       - RABBITMQ_DEFAULT_USER=RabbitMqUser
>       - RABBITMQ_DEFAULT_PASS=Pass@word34
>     volumes:
>       - rabbitmq-data:/var/lib/rabbitmq
>     ports:
>       - 45672:5672
>       - 45674:15672 # managment plugin
>     networks:
>       - network
>           
> volumes:  
>   rabbitmq-data:
> 
> networks:
>   network:
> 

Command : 
> docker-compose -p TestBug -f docker-compose.test.rabbitmq.yml up -d --build
> docker ps
--> CONTAINER ID   IMAGE                                        
--> d6c0c157275b   rabbitmq:3.8.9

This container should be based on **rabbitmq:3.8.9-management** and not on **rabbitmq:3.8.9**

**Comment by ndeloof** [comment]
I think I get it:
`$RABBITMQ_VERSION-management` syntax actually means "variable RABBITMQ_VERSION, defaults to `management` if not set" (see https://docs.docker.com/compose/environment-variables/#substitute-environment-variables-in-compose-files)

defining variable without explicit `${}` makes this syntax ambiguous, so the confusion here. Better use `${RABBITMQ_VERSION}-management` to make the variable boudaries explicit within this composed value

**Comment by ndeloof** [comment]
As a side-note, while docker-compose python only applies bash-style rules to braced variables, compose-go doesn't. I wonder this is something we should fix @ulyssessouza ?

**Comment by ulyssessouza** [comment]
I agree that it should only apply with the strict mode (the one with `${}`), otherwise that become ambiguous. Even the documentation only uses this notation. I can have a look at `godotenv` to check how hard it is to distinguish between the 2 and apply the default.

**Comment by ndeloof** [comment]
This isn't godotenv but https://github.com/compose-spec/compose-go/blob/de56f4f0cb3c925f41df594221148613534c2cd3/template/template.go#L30-L32

**Comment by ndeloof** [comment]
I've been looking into docker-compose (v1) to check the implementation details and ensure we do the same with compose-go.
This is unclear to me why [regex used `[_a-z][_a-z0-9]*`](https://github.com/docker/compose/blob/2011bc3cea1c78eccd0fa75d01a6b638d6bfb7c2/compose/config/interpolation.py#L97) would only match `RABBITMQ_VERSION` and not the whole string `RABBITMQ_VERSION-management`, failing to find an env variable for substitution.
