### ISSUE TITLE
CTRL-C does not end compose logs -f

### ISSUE THREAD

**Issue by logopk** [docker/compose#8880]
CTRL-C does not end compose logs -f

This started with compose 2.1.0

**Steps to reproduce the issue:**
1. docker-compose logs -f containername
2. CTRL-C 

whereas docker logs -f containername works as expected

**Describe the results you received:**
Command can only be killed

**Describe the results you expected:**
Return to shell

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```
Docker Compose version 2.1.0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.0)
  compose: Docker Compose (Docker Inc., 2.1.0)

Server:
 Containers: 5
  Running: 5
  Paused: 0
  Stopped: 0
 Images: 18
 Server Version: 20.10.10
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b46e404f6b9f661a205e28d59c982d3634148f8
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.0-9-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.936GiB
 Name: debian
 ID: FJ7Z:235F:BJJA:OYFZ:6SRB:6XWR:U3JO:SCBH:EQ4G:G55K:2KQL:5JK2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Default Address Pools:
   Base: 172.16.0.0/16, Size: 24
```

**Additional environment details:**

**Comment by ndeloof** [comment]
ouch, this is a regression - seems to me I've fixed this at least twice in the past :P

**Comment by nocive** [comment]
Possible duplicate of https://github.com/docker/compose/issues/8749
@ndeloof I reported this very same problem back in early October and the issue persists even after the last change (https://github.com/docker/compose/pull/8726), with slightly different symptoms.

**Comment by sy6sy2** [comment]
I can confirm that to exit from a `docker compose logs -f` we need to press multiple times CTRL-C until we get a `got 3 SIGTERM/SIGINTs, forcing shutdown`. And it happens if services are still running.

`docker compose version`: docker Compose version v2.1.1

**Comment by nocive** [comment]
I wouldn't mind having to press CTRL^C multiple times for the time being, what bothers me the most is the stale process that is left behind as described in https://github.com/docker/compose/issues/8749.
At the moment compose logs is simply unusable without some kind of shell wrapper that ensures the process termination, eg:
```bash
trap cleanup EXIT

function cleanup() {
    if [ -n "$pid" ]; then
        pkill -P $pid --signal 9
        kill -9 $pid
    fi
}

docker compose logs --tail="${nr_lines}" ${opts[@]} ${sources} 2>&1 &
pid=$!
wait $pid
```

**Comment by ndeloof** [comment]
CTRL^C multiple times just kill the client.
This is definitively a bug.

If you're running on Docker Desktop, could you please try running `com.docker.cli compose logs -f` to reproduce this issue, in case there's any relation with badly named "compose-cli" that implements the `docker` command.

**Comment by dmp1ce** [comment]
On Arch Linux "docker-compose logs -f" cannot be exited with multiple CTRL-C but "docker compose logs -f" can be exited with three CTRL-C.

**Comment by sy6sy2** [comment]
Using `com.docker.cli compose logs -f`, like `docker compose logs -f`, also leads to the `got 3 SIGTERM/SIGINTs, forcing shutdown` bug.

**Comment by davidmroth** [comment]
Same issue here on both Docker Desktop (Mac M1) and Docker installed on Ubuntu 20.04.3 LTS.  `ctrl+c` doesn't stop logs

`
$ docker version
`

`
Client:
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d28e
 Built:             Wed Aug  4 21:27:11 2021
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Wed Aug  4 21:28:41 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          v1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
`

`
$ docker-compose version
`
Docker Compose version v2.1.1
`

`

**Comment by slhck** [comment]
Thanks for the fix, this bug was driving me insane. Any ETA on when this will be released?

**Comment by Rogdham** [comment]
@slhck released as of version 2.2.0.

However the issue is not completely fixed, see #8977.

**Comment by crux** [comment]
I have the same issues with docker logs -f .... (without the compose). 

BUT! com.docker.cli works with a Ctrl-C. 

BUT! What about Ctrl-Z ? When I do a docker logs -f ...  it kind of works with a Ctrl-C, but when I try to do a Ctrl-Z before, any Ctrl-C after that will fail. 

cmd.docker.cli is an improvement over this, but still, I would like to use full job control, with Ctrl-Z backgrounding the process. WTF is going on here?

**Comment by Radiergummi** [comment]
<img width="382" alt="Bildschirmfoto 2022-10-14 um 10 56 31" src="https://user-images.githubusercontent.com/6115429/195806371-a2f5cf87-3cba-4adf-ac9a-d606ffb41ec3.png">

_Still_ experiencing this...

**Comment by garritfra** [comment]
Not sure if this is related, but I just started seeing this problem when trying to exit a regular `docker-compose up`.

**Comment by jspiers** [comment]
I'm seeing this same bug (i.e. after starting containers using `docker compose up -d` and viewing logs with `docker logs -f <container_name>`, I need 3 Ctrl-C keypresses to quit viewing the logs, and this results in an orphaned "docker-compose" process).

```
$ docker version
Client: Docker Engine - Community
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:28:04 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:25:49 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.13
  GitCommit:        78f51771157abb6c9ed224c22013cdf09962315d
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by Lemmmy** [comment]
> and this results in an orphaned "docker-compose" process

Oh wow, you weren't kidding

![image](https://user-images.githubusercontent.com/858456/208305500-51a1d3a7-da54-42e6-a2ca-ac961e28ab6e.png)

**Comment by lungj** [comment]
Does `SIGQUIT` (CTRL+\) leave any orphans for you @Lemmmy ?

**Comment by Lemmmy** [comment]
No, it does not

**Comment by jonwest** [comment]
Having the same issue here with both `docker compose logs -f` and `docker compose up`.

**Comment by gertcuykens** [comment]
same issue 
Docker Compose version v2.14.1
Client: Docker Engine - Community
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:28:22 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

**Comment by ndeloof** [comment]
This has been fixed in 2.14.2, see https://github.com/docker/compose/pull/10104

**Comment by garritfra** [comment]
@ndeloof thanks, I can confirm that the issue is fixed.

**Comment by ndeloof** [comment]
👍

**Comment by oxxxxxy** [comment]
lol, nope.

> [@ndeloof](https://github.com/ndeloof) thanks, I can confirm that the issue is fixed.

**Comment by shanec42** [comment]
I'm seeing this problem again on Docker Compose version v2.39.1.  The problem only happens with 'docker compose logs -f'.  It takes 2 ^C intrupts to break out.  If you do a 'docker logs -f' a single ^C will break out just fine.

Doing a SIGQUIT (^\) works immediately. 

root@fenchurch: dpkg --list | egrep -i "docker|container"
ii  containerd.io                             1.7.27-1                                amd64        An open and reliable container runtime
ii  docker-buildx-plugin                      0.26.1-1~ubuntu.24.04~noble             amd64        Docker Buildx cli plugin.
ii  docker-ce                                 5:28.3.3-1~ubuntu.24.04~noble           amd64        Docker: the open-source application container engine
ii  docker-ce-cli                             5:28.3.3-1~ubuntu.24.04~noble           amd64        Docker CLI: the open-source application container engine
ii  docker-ce-rootless-extras                 5:28.3.3-1~ubuntu.24.04~noble           amd64        Rootless support for Docker.
ii  docker-compose-plugin                     2.39.1-1~ubuntu.24.04~noble             amd64        Docker Compose (V2) plugin for the Docker CLI.
ii  libavformat60:amd64                       7:6.1.1-3ubuntu5+esm3                   amd64        FFmpeg library with (de)muxers for multimedia containers - runtime files
ii  libmatroska7:amd64                        1.7.1-1build1                           amd64        extensible open standard audio/video container format (shared library)
ii  libnvidia-container-tools                 1.17.8-1                                amd64        NVIDIA container runtime library (command-line tools)
ii  libnvidia-container1:amd64                1.17.8-1                                amd64        NVIDIA container runtime library
ii  nvidia-container-toolkit                  1.17.8-1                                amd64        NVIDIA Container toolkit
ii  nvidia-container-toolkit-base             1.17.8-1                                amd64        NVIDIA Container Toolkit Base
ii  python3-sortedcontainers                  2.4.0-2                                 all          sorted container types: SortedList, SortedDict, and SortedSet (Python 3)


root@fenchurch: cat /etc/issue
Ubuntu 24.04.3 LTS \n \l

root@fenchurch: uname -a
Linux fenchurch 6.8.0-71-generic #71-Ubuntu SMP PREEMPT_DYNAMIC Tue Jul 22 16:52:38 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Aransh** [comment]
+1
Was going crazy on whether this has always been this way and I’ve just started noticing 😵‍💫
Can this please be reopened?

**Comment by DerDreschner** [comment]
That bug is still there in version 2.37.1+ds1-0ubuntu2~24.04.1.

**Comment by ndeloof** [comment]
@DerDreschner 2.37 is outdated, better use https://docs.docker.com/engine/install/ubuntu/
