### ISSUE TITLE
Docker Compose V2 `up` does not allow a dot in a project name

### ISSUE THREAD

**Issue by DaleyKD** [docker/compose#8881]
**Description**
Docker Compose V2 does not allow a period/dot in a project name when using the `up` command.

**Steps to reproduce the issue:**
1. `docker compose -p my.project up`

**Describe the results you received:**
Notice that the project name ends up being just "my".

**Describe the results you expected:**
The project name should be "my.project."  Please note, it worked this way in beta versions of V2.

**Additional information you deem important (e.g. issue happens only occasionally):**
When running `docker compose -p my.project down`, it attempts to stop/remove "my.project" instead of "my".  So, there's a discrepancy between `up` and `down`.

**Output of `docker compose version`:**
```
PS C:\> docker compose version
Docker Compose version v2.0.0
```

**Output of `docker info`:**
```
PS C:\> docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.3)
  compose: Docker Compose (Docker Inc., v2.0.0)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 5
  Running: 5
  Paused: 0
  Stopped: 0
 Images: 62
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.47-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 7
 Total Memory: 23.49GiB
 Name: docker-desktop
 ID: JDMB:56T7:3WIK:ZVF6:DCOW:GJUW:6TGO:CPUY:4GEX:JPIY:AJG3:J6VE
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**

**Comment by ndeloof** [comment]
This has been fixed by https://github.com/compose-spec/compose-go/pull/197

**Comment by DaleyKD** [comment]
Thanks!

**Comment by DaleyKD** [comment]
I tested again in Docker Desktop 4.2.0 (70708). Still an issue. Not sure when this is going to be released.
