### ISSUE TITLE
Error during pull

### ISSUE THREAD

**Issue by isvaljek** [docker/compose#9448]
This error occurs during docker compose pull with --context argument

**Steps to reproduce the issue:**
1. docker --context mycontext compose -f docker-compose.letsencrypt.yml pull
2. error during connect: Get "http://docker.example.com/v1.41/images/mongo-express/json": command [ssh -l root -- pharma-bio.hr docker system dial-stdio] has exited with exit status 255, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=kex_exchange_identification: Connection closed by remote host

**Describe the results you received:**
error during connect: Get "http://docker.example.com/v1.41/images/mongo-express/json": command [ssh -l root -- pharma-bio.hr docker system dial-stdio] has exited with exit status 255, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=kex_exchange_identification: Connection closed by remote host

**Describe the results you expected:**
Normal pull of all images, both from my docker hub and public ones

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```
Docker Compose version v2.4.1
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2)
  compose: Docker Compose (Docker Inc., v2.4.1)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 22
  Running: 13
  Paused: 0
  Stopped: 9
 Images: 111
 Server Version: 20.10.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.60.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 20
 Total Memory: 15.52GiB
 Name: docker-desktop
 ID: MGP6:OKSX:HXN5:OL2J:CK7W:OJQ2:HTGL:COC7:OFZY:DYIQ:HZNR:UB35
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

**Additional environment details:**
I'm using Ubuntu 20.04 WSL on client side, and deploying to Ubuntu server 20.04 (both sides fully patched).

**Comment by glours** [comment]
What did you get if you try to run `docker --context mycontext  pull an_image_from_compose_file` ?

**Comment by miroslavmachura** [comment]
I'm also hitting this issue, it happens for both `ssh` and `tcp` contexts.

**Comment by zachberger** [comment]
What is strange is I *don't* see this with v2.4.1 as noted in #9435, however this issue, #9448, seems to reproduce it on that build

**Comment by hansbogert** [comment]
> What is strange is I _don't_ see this with v2.4.1 as noted in #9435, however this issue, #9448, seems to reproduce it on that build

I am experiencing the same. But the 'non-popularity' of this issue seems strange. Is there a hidden common factor just for us? Seems easy to reproduce though.

Maybe not a lot of persons are using d-compose v2.5.0 icw remote SSH.

**Comment by Benjamin-Tan** [comment]
In #8544, the comment suggested to use remote docker context with unix:// (unix socket forwarding over the SSH connection) instead of ssh:// seems to a possible workaround. 
https://github.com/docker/compose/issues/8544#issuecomment-974639028

**Comment by zachberger** [comment]
Still reproducible in 2.6.0

**Comment by figure002** [comment]
I suddenly run into the same issue in GitLab pipelines. The pipeline looks like this:

```
accept-deploy:
  image: docker:latest
  stage: accept
  variables:
    DOCKER_HOST: ssh://gitlab@example.com
  before_script:
    - apk update && apk add docker docker-compose openssh-client
    - ...
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
  script:
    - docker-compose build --pull
    - docker-compose pull
    - docker-compose up -d
```

And the error message:

```
$ docker-compose pull
time="2022-06-13T08:42:05Z" level=warning msg="network public: network.external.name is deprecated in favor of network.name"
nginx Skipped 
uwsgi Pulling 
postgres Pulling 
time="2022-06-13T08:42:05Z" level=warning msg="commandConn.CloseWrite: commandconn: failed to wait: signal: killed"
postgres Error 
uwsgi Error 
error during connect: Post "http://docker.example.com/v1.41/images/create?fromImage=postgres&tag=13-alpine": command [ssh -l gitlab -- example.com docker system dial-stdio] has exited with signal: killed, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=
```

This pipeline used to work just fine about a month ago. The Docker Compose version on Alpine Linux a month ago was `1.29.2-r1`, but now it's `1.29.2-r2`.

**Comment by figure002** [comment]
I manged to fix this for now by reverting to an older Docker image:

Latest working version: `docker:20.10.14`
Broken for: `docker:20.10.15` and later.

**Comment by ivlis** [comment]
I have the example same error. 2.4.1 works just fine, fails to pull on and after 2.5.0.

Please fix this!

**Comment by etienned** [comment]
I can confirm that the 2.4.1 version works. So there's some chances that the problem come from this change: 
https://github.com/docker/compose/commit/625a48dcf712f52e1aae64cd664a97699a4fe5bf

**Comment by fergalmoran** [comment]
Also have this issue with 2.7.0

**Comment by zachberger** [comment]
This continues on 2.8.0

**Comment by zachberger** [comment]
@ndeloof could you PTAL since this seems related to 625a48d?

**Comment by glours** [comment]
I tried to reproduce with a very(too?) simple example to reproduce.
I setup an multipass ubuntu VM with a rootless docker installation via t[he convenience script of the official documentation](https://docs.docker.com/engine/install/ubuntu/#install-using-the-convenience-script). Then I configure thdocker  service to be available via tcp.

In the following screenshot, the left tab is the vm displaying `docker info`, you can see that I'm using a `20.10.17` engine and Compose `v2.6.0`
note the warning about the API accessible without encryption (I said simple test 😅)
![Screenshot 2022-08-02 at 11 00 37](https://user-images.githubusercontent.com/705411/182336133-4e329818-b7bf-45bf-ad10-9fa70ce5a0fa.png)

Can you test the same example and maybe you'll be able to give me more context/hints to reproduce your issue?
here the compose file used:
```yaml
services:
  common:
    image: busybox
    environment:
      TZ: utc
      PORT: 80
```

**Comment by glours** [comment]
@ivlis works as expected on my side 🤔 
![Screenshot 2022-08-02 at 14 22 55](https://user-images.githubusercontent.com/705411/182373572-2f648810-356f-4acb-9568-6f8d387d8ef7.png)

**Comment by zachberger** [comment]
@glours what about with a ssh context instead of tcp context?

**Comment by ivlis** [comment]
@glours @zachberger 

Here is a minimal example demonstrating the problem. It seems it deals with the custom repositories.

this does not work:
```
version: '3.9'
services:
  hass:
    image: ghcr.io/home-assistant/home-assistant:2022.7.5
  ubuntu:
    image: ubuntu
```

```
docker --context xxxx compose  -f ./docker-compose-bad.yml pull
WARN[0000] commandConn.CloseWrite: commandconn: failed to wait: signal: killed 
[+] Running 0/0
 ⠿ hass Error                                                                                                                0.0s
 ⠿ ubuntu Error                                                                                                              0.0s
error during connect: Post "http://docker.example.com/v1.41/images/create?fromImage=ubuntu&tag=latest": command [ssh -l user -- xxxx docker system dial-stdio] has exited with signal: killed, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=
```
But commenting out either one of the services results in a successful pull.

```
docker context inspect xxxx
[
    {
        "Name": "xxxx",
        "Metadata": {},
        "Endpoints": {
            "docker": {
                "Host": "ssh://user@xxxx",
                "SkipTLSVerify": false
            }
        },
        "TLSMaterial": {},
        "Storage": {
            "MetadataPath": "/home/ivlis/.docker/contexts/meta/1f54ca1cf12c1f6a1c7c11ab42fe5b58e6bddead8e8024e3a4d9cd7ef345ff55",
            "TLSPath": "/home/ivlis/.docker/contexts/tls/1f54ca1cf12c1f6a1c7c11ab42fe5b58e6bddead8e8024e3a4d9cd7ef345ff55"
        }
    }
]
```

**Comment by glours** [comment]
@ivlis @zachberger no issue with ssh also, and I used @ivlis compose file for this test
I also had the warning message but was able to pull the 2 images
```shell
> bat compose.yaml
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: compose.yaml
       │ Size: 104 B
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ services:
   2   │   hass:
   3   │     image: ghcr.io/home-assistant/home-assistant:2022.7.5
   4   │   ubuntu:
   5   │     image: ubuntu
───────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────
> docker --context=remote-engine compose pull
WARN[0000] commandConn.CloseWrite: commandconn: failed to wait: signal: killed
[+] Running 30/30
 ⠿ hass Pulled                                                                                                  42.4s
   ⠿ b3c136eddcbf Pull complete                                                                                  0.9s
   ⠿ 7ccb820019d9 Pull complete                                                                                  0.9s
   ⠿ 7946c12c8fa4 Pull complete                                                                                  2.6s
   ⠿ d8668b875010 Pull complete                                                                                  2.6s
   ⠿ 7f072ea1c427 Pull complete                                                                                  5.7s
   ⠿ 90b8edde1fa7 Pull complete                                                                                  5.7s
   ⠿ c53f79b7d344 Pull complete                                                                                  6.1s
   ⠿ 78f64f24b1ea Pull complete                                                                                  7.6s
   ⠿ 1f7441c5835c Pull complete                                                                                  7.7s
   ⠿ da41e69aeaed Pull complete                                                                                  7.9s
   ⠿ f7aa1915a47f Pull complete                                                                                  8.0s
   ⠿ 9aebc1dab72e Pull complete                                                                                  8.0s
   ⠿ ba965dcd5383 Pull complete                                                                                  8.0s
   ⠿ 8f9e054f1555 Pull complete                                                                                  8.1s
   ⠿ 22a1b6a1c0b4 Pull complete                                                                                  8.2s
   ⠿ 79cb73331227 Pull complete                                                                                  8.3s
   ⠿ 7fea82b91979 Pull complete                                                                                  8.3s
   ⠿ 39c2416e5f59 Pull complete                                                                                  8.3s
   ⠿ 2b4ea8f2c2f8 Pull complete                                                                                  8.4s
   ⠿ 8aba4297a7c0 Pull complete                                                                                  8.6s
   ⠿ 17bb02260fae Pull complete                                                                                  9.4s
   ⠿ f6cdded59d63 Pull complete                                                                                  9.4s
   ⠿ 62744569fdaf Pull complete                                                                                 31.2s
   ⠿ 8940cac1884a Pull complete                                                                                 33.8s
   ⠿ 7b610ca278fd Pull complete                                                                                 34.7s
   ⠿ 27bc02b17114 Pull complete                                                                                 34.8s
   ⠿ 967057c052b4 Pull complete                                                                                 34.8s
 ⠿ ubuntu Pulled                                                                                                 7.8s
   ⠿ 4a3049d340b7 Pull complete                                                                                  2.6s
> docker context inspect remote-engine
[
    {
        "Name": "remote-engine",
        "Metadata": {},
        "Endpoints": {
            "docker": {
                "Host": "ssh://ubuntu@192.168.64.4",
                "SkipTLSVerify": false
            }
        },
        "TLSMaterial": {},
        "Storage": {
            "MetadataPath": "/Users/glours/.docker/contexts/meta/7619d3b88f9c1911b5599a392f472255651c39a73ffc5db4101815caa3295ee5",
            "TLSPath": "/Users/glours/.docker/contexts/tls/7619d3b88f9c1911b5599a392f472255651c39a73ffc5db4101815caa3295ee5"
        }
    }
]
```

**Comment by zapotocnylubos** [comment]
Hello, I have been trying to get ssh docker compose deployment (pull is the first step) working for days now. I have tried the connection to and from 4 new fresh VMS - the latest Debian, latest ubuntu, and latest arch.

None of these connections worked, but I have now tried to just spam and do over and over `docker compose pull` with remote context, and approximately in **1 of 10 tries**, the pull actually gets started and finishes without a problem. But why in **9 of 10** cases ssh connection interrupts and the docker compose pull does not even start? Could this be an issue with **server sshd configuration?** I have always used the default ubuntu/Debian/arch sshd configuration without any modification. Or even with networking (packet size etc.)?

```
[zapotocnylubos@workstation docker-ssh-test]$ docker compose pull 
WARN[0000] commandConn.CloseWrite: commandconn: failed to wait: signal: killed 
[+] Running 0/0
 ⠿ hass Error                                                                                                                                                              0.0s
 ⠿ ubuntu Error                                                                                                                                                            0.0s
error during connect: Post "http://docker.example.com/v1.41/images/create?fromImage=ubuntu&tag=latest": command [ssh -l zapotocnylubos -- 10.0.1.106 docker system dial-stdio] has exited with signal: killed, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=
[zapotocnylubos@workstation docker-ssh-test]$ docker compose pull 
WARN[0000] commandConn.CloseWrite: commandconn: failed to wait: signal: killed 
[+] Running 0/0
 ⠿ ubuntu Error                                                                                                                                                            0.0s
 ⠿ hass Error                                                                                                                                                              0.0s
error during connect: Post "http://docker.example.com/v1.41/images/create?fromImage=ubuntu&tag=latest": command [ssh -l zapotocnylubos -- 10.0.1.106 docker system dial-stdio] has exited with signal: killed, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=
[zapotocnylubos@workstation docker-ssh-test]$ docker compose pull 
WARN[0000] commandConn.CloseWrite: commandconn: failed to wait: signal: killed 
[+] Running 0/0
 ⠿ ubuntu Error                                                                                                                                                            0.0s
 ⠿ hass Error                                                                                                                                                              0.0s
error during connect: Post "http://docker.example.com/v1.41/images/create?fromImage=ubuntu&tag=latest": command [ssh -l zapotocnylubos -- 10.0.1.106 docker system dial-stdio] has exited with signal: killed, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=
[zapotocnylubos@workstation docker-ssh-test]$ docker compose pull 
WARN[0000] commandConn.CloseWrite: commandconn: failed to wait: signal: killed 
[+] Running 0/0
 ⠿ ubuntu Error                                                                                                                                                            0.0s
 ⠿ hass Error                                                                                                                                                              0.0s
error during connect: Post "http://docker.example.com/v1.41/images/create?fromImage=ubuntu&tag=latest": command [ssh -l zapotocnylubos -- 10.0.1.106 docker system dial-stdio] has exited with signal: killed, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=
[zapotocnylubos@workstation docker-ssh-test]$ docker compose pull 
WARN[0000] commandConn.CloseWrite: commandconn: failed to wait: signal: killed 
[+] Running 0/0
 ⠿ ubuntu Error                                                                                                                                                            0.0s
 ⠿ hass Error                                                                                                                                                              0.0s
error during connect: Post "http://docker.example.com/v1.41/images/create?fromImage=ubuntu&tag=latest": command [ssh -l zapotocnylubos -- 10.0.1.106 docker system dial-stdio] has exited with signal: killed, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=
[zapotocnylubos@workstation docker-ssh-test]$ docker compose pull 
WARN[0000] commandConn.CloseWrite: commandconn: failed to wait: signal: killed 
[+] Running 0/0
 ⠿ hass Error                                                                                                                                                              0.0s
 ⠿ ubuntu Error                                                                                                                                                            0.0s
error during connect: Post "http://docker.example.com/v1.41/images/create?fromImage=ubuntu&tag=latest": command [ssh -l zapotocnylubos -- 10.0.1.106 docker system dial-stdio] has exited with signal: killed, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=
[zapotocnylubos@workstation docker-ssh-test]$ docker compose pull 
WARN[0000] commandConn.CloseWrite: commandconn: failed to wait: signal: killed 
[+] Running 0/0
 ⠿ hass Error                                                                                                                                                              0.0s
 ⠿ ubuntu Error                                                                                                                                                            0.0s
error during connect: Post "http://docker.example.com/v1.41/images/create?fromImage=ubuntu&tag=latest": command [ssh -l zapotocnylubos -- 10.0.1.106 docker system dial-stdio] has exited with signal: killed, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=
[zapotocnylubos@workstation docker-ssh-test]$ docker compose pull 
WARN[0000] commandConn.CloseWrite: commandconn: failed to wait: signal: killed 
[+] Running 0/0
 ⠿ hass Error                                                                                                                                                              0.0s
 ⠿ ubuntu Error                                                                                                                                                            0.0s
error during connect: Post "http://docker.example.com/v1.41/images/create?fromImage=ubuntu&tag=latest": command [ssh -l zapotocnylubos -- 10.0.1.106 docker system dial-stdio] has exited with signal: killed, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=
[zapotocnylubos@workstation docker-ssh-test]$ docker compose pull 
WARN[0000] commandConn.CloseWrite: commandconn: failed to wait: signal: killed 
[+] Running 0/2
 ⠋ ubuntu Pulling                                                                                                                                                          1.0s
 ⠋ hass Pulling                                                                                                                                                            1.0s
   ⠋ 2408cc74d12b Pulling fs layer 
```

**Comment by zapotocnylubos** [comment]
Weirdly enough, the same setup **works every time** from my local MacBook via ssh to a remote Linux server.

Mac: `Docker Compose version v2.7.0`
Remote Workstation (Archlinux): `Docker Compose version 2.9.0`

But from Linux to Linux server, it works only in 1 of 10 attempts.

**Comment by demonshreder** [comment]
My setup - deploy containers from one remote server to another via local IP SSH. docker-compose always works for replicas until 10 or 11. Any number more than that fails 8 out of 10 times.

**Comment by Oblosys** [comment]
I ran into these errors ~75% of the time when doing a docker-compose ps over ssh from an M1 Mac to an ubuntu machine. They also happened during other docker-compose commands over ssh, and using context or `DOCKER_HOST` made no difference.

Thanks to [this comment](https://github.com/docker/compose/issues/8191#issuecomment-1022725507), I finally managed to get rid of them completely, by putting

```
MaxStartups 500
```

in `/etc/ssh/sshd_config` on the ubuntu target (followed by a `sudo service ssh restart`).

**Comment by zachberger** [comment]
Wow! that fixed it for me too. My Synology was set to `10:50:100`

**Comment by mahnunchik** [comment]
Any news?

**Comment by mahnunchik** [comment]
The same issue on: `compose: Docker Compose (Docker Inc., v2.11.2)`

**Comment by 9r1nc3w1ll** [comment]
I got around this by locking the docker compose version to v2.3.3. Every other suggestion here failed.
Using Github actions, this is what the job looks like.
```
      - name: Setup Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl gnupg lsb-release
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin=2.3.3~ubuntu-focal
```

I hope this helps.

**Comment by pdaig** [comment]
I also have the issue. It's intermittent but I'm able to reproduce it about 9/10 times.

> error during connect: Post "http://docker.example.com/v1.41/images/create?fromImage=docker&tag=latest": command [ssh -l user -- host docker system dial-stdio] has exited with signal: killed, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=

After some (lots) of trial and errors and poking around, I think I've found the cause and some possible solution. I tried the `MaxStartups 500` fix above, but it didn't solve the issue for me (in fact the problem seems to be on the client, see below).

**TLDR**: it's some kind of race condition with the ssh process spawned on the client.

### Minimal repro steps
``` yml docker-compose.yml
version: "3.9"
services:
  docker:
    image: docker
  alpine:
    image: alpine
```
``` bash
docker -H ssh://[user]@[host] compose pull
OR
DOCKER_HOST=ssh://[user]@[host] docker compose pull
```
Environment (client)
* Latest docker image (15b7f46c4c94)
  OR
* Ubuntu 20.04 with docker-ce-cli `5:20.10.18~3-0~ubuntu-focal`

As the error message points out, a command is "killed" while doing the pull. By tracing the docker daemon logs (`journalctl -fxu docker.service` on the remote machine) and comparing a successful attempt with a failed attempt, I found out that some of the requests sent by the client were never received by the daemon.

Since there were no signs of a process being killed or any sign of an issue on the remote, it had to be on the client. But what could possibly kill the ssh client ? I used [auditctl](https://www.thegeekdiary.com/how-to-find-which-process-is-killing-mysqld-with-sigkill-or-sigterm-on-linux/) to find out. The answer is a bit surprising : it's the `docker-compose` binary itself (which is the parent process) !

### Digging further:

As some previous comments suggested, this commit [`625a48d`](https://github.com/docker/compose/commit/625a48dcf712f52e1aae64cd664a97699a4fe5bf#diff-2a6b4d85b4172a20829d65bb72126a9402faf6490ee556964f6a4e167cf3a8bbR58-R62) indeed triggers the issue, specifically lines 58-62. Commenting out these lines seems to completely fix the issue.

I print-debugged my way to understand what exactly was going on. Here's what I _think_ is happening:
Disclaimer: I don't have much experience in Go (in fact, never used it before) so my comprehension might be flawed. Please correct me, if I'm wrong.

1. The call to [`getLocalImagesDigests`](https://github.com/docker/compose/blob/v2.11.2/pkg/compose/build.go#L193) in turn calls [`getImages`](https://github.com/docker/compose/blob/v2.11.2/pkg/compose/images.go#L80):
  The for loop starts many goroutines in parallel which are then awaited before returning.
  ``` go
  eg, ctx := errgroup.WithContext(ctx)
  for _, img := range images {
    img := img
    eg.Go(func() error {
      inspect, _, err := s.apiClient().ImageInspectWithRaw(ctx, img)
      // ... returns err or nil
    })
  }
  return summary, eg.Wait()
  ```
2. Each call to [`ImageInspectWithRaw`](https://github.com/moby/moby/blob/v20.10.18/client/image_inspect.go#L13) ends up spawning a new ssh connection. The http request is piped through ssh to `docker system dial-stdio` on the remote. In the docker cli, [`commandconn.go`](https://github.com/docker/cli/blob/v20.10.18/cli/connhelper/commandconn/commandconn.go#L40) : the command is passed the shared `Context` from the `errgroup` in the caller (this will be important later).
3. The goroutine executes the http request and returns once the whole response body is read.
4. When all goroutine finish the call to `eg.Wait()` unblocks and the shared `Context` (linked to each ssh command) becomes `Done()`.
5. As [documented](https://pkg.go.dev/os/exec#CommandContext), the context's completion kills the process.
6. Even thought the whole http response body has been read and the goroutine has returned, the ssh process is still running because Go's http client implementation seems to keep the `net.Conn` open (in this case, the ssh `commandConn`) - maybe even reuses it (?). It still tries to read `stdout`:
   ```
    github.com/docker/cli/cli/connhelper/commandconn.(*commandConn).onEOF(0xc0000bf080, {0x20404c0?, 0xc0000a2120})
        github.com/docker/cli@v20.10.17+incompatible/cli/connhelper/commandconn/commandconn.go:216 +0x4fb
    github.com/docker/cli/cli/connhelper/commandconn.(*commandConn).Read(0xc0000bf080, {0xc000535000, 0x0?, 0x1000})
        github.com/docker/cli@v20.10.17+incompatible/cli/connhelper/commandconn/commandconn.go:268 +0x28c
    net/http.(*persistConn).Read(0xc000695c20, {0xc000535000?, 0xc000520ba0?, 0xc0005afd30?})
        net/http/transport.go:1929 +0x4e
    bufio.(*Reader).fill(0xc0005bca20)
        bufio/bufio.go:106 +0xff
    bufio.(*Reader).Peek(0xc0005bca20, 0x1)
        bufio/bufio.go:144 +0x5d
    net/http.(*persistConn).readLoop(0xc000695c20)
        net/http/transport.go:2093 +0x1ac
    created by net/http.(*Transport).dialConn
        net/http/transport.go:1751 +0x173e
   ```
   (line numbers in the stack trace won't match for `commandconn.go` due to some logs I sprinkled around)
8. We end up in [`onEOF`](https://github.com/docker/cli/blob/v20.10.18/cli/connhelper/commandconn/commandconn.go#L145), where we wait for the process to exit normally but it fails because it was previously killed.
   ``` go
   go func() { werrCh <- c.cmd.Wait() }()
   ```
   On line 165, the observed error message is returned to the caller, the whole `errgroup` fails and everything is aborted.

### Solutions

1. ❌ Linking the `Context` to the command is what causes the process to be killed. However, I think it's legitimate to do so in case there's an actual error. All requests run in parallel and all needs to succeeds in order to continue. If one of them fails, we want to kill/cancel the others to avoid unnecessary waiting.
2. 💡 It would be nice if there was a way that `errgroup.Wait()` would not set the `Context` to _done_ when there is no error. Or some way to know if the `Context` is _done_ because of an error or because everything completed successfully. Then with a small change we could kill the command only in the case of an error.
  In theory, this would allow connection reuse (so potentially faster). The ssh process would keep running after the request/response completes. Subsequent request could then be run through it (`docker system dial-stdio` seems to support multiple requests on the same session). IMO, this would be the ideal solution if doable (preferable to solution # 4 below).
3. ❌ Not running things in parallel : this would slow things down.
4. ✅ Actually close the `net.Conn` before the goroutine returns - not just finish reading the response. I found that calling [`CloseIdleConnections`](https://pkg.go.dev/net/http#Client.CloseIdleConnections) properly [closes](https://github.com/docker/cli/blob/v20.10.18/cli/connhelper/commandconn/commandconn.go#L225) the `commandConn`.
   Just before returning from [`ImageInspectWithRaw`](https://github.com/moby/moby/blob/v20.10.18/client/image_inspect.go#L31), I added `cli.client.CloseIdleConnections()` and it completely fixed the issue 🎉
   However, since this could theoretically also happen in other functions, there is probably a better place to put this. Maybe somewhere in [`request.go`](https://github.com/moby/moby/blob/v20.10.18/client/request.go) ? Since this needs to happen _after_ the body is completely read, there would need to be a way to detect that.

I know this is a lot of things to digest for what looks like a complicated issue, but could someone confirm some of this and chime in on the possible solutions ? Help is welcome to get a PR started :)

One of the reasons I dedicated this much time to investigate the issue is because our CI pipeline rely on this behavior for deployments. Having it fail _most_ of the time is not ideal to say the least ;)

**Comment by mahnunchik** [comment]
@pdaig minimal example works as expected with client on macos.

Engine: 20.10.17
Compose: v2.10.2

But doesn't work on gitlab CI.

**Comment by pdaig** [comment]
@mahnunchik

macos -> maybe something to do with how "quickly" the os handles the kill signal and closes stdout ? I don't know...

Couldn't reproduce the issue either when pulling a single image. Debugging it I can see that the `Context` of the `errgroup` is set to _done_. However, no read attempt returns `EOF` so that's why it works.

I noticed that all requests made during the pull go through the same ssh process (same PID). So the same connection is reused for all requests. The first request (`HEAD /_ping`) establishes the connection and it's the `Context` passed in _at this point_ that gets linked to the process. This context never seems to get set to _done_. The context passed by the `errgroup` isn't linked to the process (the first one is) so when it gets _done_ it doesn't kill it.

Also, `commandConn.Close()` is never called so it would seem the process never gets cleanly shut down? In the end, I guess everything gets cleaned up either by go and/or the os. There's no remaining ssh process after `docker compose` exits.

All in all, it seems to make sense.

**Comment by lUNuXl** [comment]
> I got around this by locking the docker compose version to v2.3.3. Every other suggestion here failed. Using Github actions, this is what the job looks like.

I can confirm this workaround works on archlinux, for anyone needing to downgrade docker-compose package:

```
wget https://archive.archlinux.org/packages/d/docker-compose/docker-compose-2.3.3-1-x86_64.pkg.tar.zst
sudo pacman -U ./docker-compose-2.3.3-1-x86_64.pkg.tar.zst
```

**Comment by mahnunchik** [comment]
@ndeloof ping

**Comment by stephanGarland** [comment]
@pdaig I can confirm that avoiding [625a48d](https://github.com/docker/compose/commit/625a48dcf712f52e1aae64cd664a97699a4fe5bf#diff-2a6b4d85b4172a20829d65bb72126a9402faf6490ee556964f6a4e167cf3a8bbR58-R62) (I did `git checkout 625a48d^ pkg/compose/pull.go) fixes the problem, _most of the time._ I was able to get this to still fail, however intermittently.

```
❯ docker version
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.19.2
 Git commit:        baeda1f82a
 Built:             Tue Oct 25 17:53:02 2022
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: linux/amd64/fedora-36
 Podman Engine:
  Version:          4.3.0
  APIVersion:       4.3.0
  Arch:             amd64
  BuildTime:        2022-10-21T04:16:35-04:00
  Experimental:     false
  GitCommit:
  GoVersion:        go1.18.7
  KernelVersion:    6.0.5-200.fc36.x86_64
  MinAPIVersion:    4.0.0
  Os:               linux
 Conmon:
  Version:          conmon version 2.1.4, commit:
  Package:          conmon-2.1.4-3.fc36.x86_64
 OCI Runtime (crun):
  Version:          crun version 1.6
commit: 18cf2efbb8feb2b2f20e316520e0fd0b6c41ef4d
spec: 1.0.0
+SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  Package:          crun-1.6-2.fc36.x86_64
 Engine:
  Version:          4.3.0
  API version:      1.41 (minimum version 1.24)
  Go version:       go1.18.7
  Git commit:
  Built:            Fri Oct 21 04:16:35 2022
  OS/Arch:          linux/amd64
  Experimental:     false
  ```
  
The error message I received:

```
[+2419] error during connect: Post "http://docker.example.com/v1.41/containers/543154281a08879f86a1eca7ef56b8e32398e8a96b573909bd683f1169bf361f/stop": command [ssh -l core -p 64596 -- localhost docker system dial-stdio] has exited with exit status 255, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=kex_exchange_identification: Connection closed by remote host
```

If it matters, the application I'm using this for is an extremely intensive collection of images, so there are quite a few connections being made over the SSH tunnel. I can provide more details as needed.

**Comment by ndeloof** [comment]
> If it matters, the application I'm using this for is an extremely intensive collection of images, so there are quite a few connections being made over the SSH tunnel

I wonder this issue could be caused by the way we run stuff concurrently without limitations. Typically, compose will pull all missing images with parallel ssh streams from client to engine. Maybe we should limit concurrency

**Comment by sam-mathews** [comment]
I'm also seeing this on:
`Docker Compose version v2.12.2` with docker version:
```
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:01:58 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 17:59:49 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.10
  GitCommit:        770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Was experiencing this problem in GitHub Actions, so I changed my local setup to reproduce. I wasn't experiencing it on `docker-compose`, but am experiencing on `docker compose`. The MaxStartups change did not make any difference to me.

Current workaround is to do:
```
docker compose pull my-image-1
docker compose pull my-image-2
``` 

Pulling images individually has also fixed my GitHub actions problem. It's good there is a workaround, but it's not particularly maintainable.

**Comment by fergalmoran** [comment]
Still an issue in 2.13.0

**Comment by pdaig** [comment]
@stephanGarland 
You may have hit another similar issue I encountered a while ago.

The error message is a bit different. Have you tried `MaxSessions 500` and/or `MaxStartups 500` as suggested above and in this [thread](https://github.com/docker/compose/issues/8191#issuecomment-1022725507) ?
This has worked for me. There's still the other issue thought, but as you already figured out, you can work around it by using a version without 625a48d.

**To summarize:**
There seems to be 2 distinct issues with a similar error message.

* The first one indicates that the ssh client process was killed (`[...] has exited with signal: killed`). This seems to be an issue with the docker client. It's the behavior I described in my previous [comment](https://github.com/docker/compose/issues/9448#issuecomment-1264263721).
  As far as I know, there's no fix yet for this one but there are workarounds:
  - Downgrade to docker compose v2.4.1 or older.
    Be aware that older versions may have other bugs that were fixed or a slight difference in behavior or might not support newer compose file syntax.
    <sub>In particular, the change to environment variable handling (#9879) introduced in v2.11.2. Depending on your use case this may or may not be a viable solution.</sub>
  - Compile a custom version and revert 625a48d
  - pull each image individually
  ```
  docker compose pull service1
  docker compose pull service2
  ...
  ```

* The other issue is related to the ssh server. The error message might include `stderr=kex_exchange_identification: Connection closed by remote host`. The docker client seems to open lots of connections and depending on your os/server configuration, you might need to bump `MaxSessions` and/or `MaxStartups` in your sshd server configuration.

**Comment by pdaig** [comment]
I found a solution. I've opened a PR in docker/cli#3900.

**Comment by ndeloof** [comment]
Closing as "fixed by https://github.com/docker/cli/pull/3900"
Thanks @pdaig 👍

**Comment by krzysieqq** [comment]
Tested on:
```
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  compose: Docker Compose (Docker Inc., v2.14.1)
  scan: Docker Scan (Docker Inc., v0.23.0)

Server:
 Containers: 21
  Running: 2
  Paused: 0
  Stopped: 19
 Images: 280
 Server Version: 20.10.22
```
and I think it isn't fixed

```
$ DOCKER_HOST=ssh://root@<server>:<port> docker compose pull
[+] Running 1/2
 ⠿ web Warning                                                                                                                                            0.0s
 ⠿ db Pulled                                                                                                                                              1.3s
WARNING: Some service image(s) must be built from source by running:
    docker compose build web
1 error occurred:
	* error during connect: Post "http://docker.example.com/v1.41/images/create?fromImage=local%2Fdjango_poll&tag=local": command [ssh -l root -p <port> -- <server> docker system dial-stdio] has exited with signal: killed, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=
```
My docker compose:
```
services:
  db:
    image: postgres
    volumes:
    - postgresql_data:/var/lib/postgresql/data
    environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
  web:
    image: ${CI_REGISTRY_IMAGE:-local/django_poll}:${CI_COMMIT_REF_SLUG:-local}
    build: .
    command: bash -c "
      python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput &&
      gunicorn django_poll.wsgi --workers 2 --bind 0.0.0.0:8000
      "
    ports:
    - "8000:8000"
    environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    depends_on:
    - db

volumes:
  postgresql_data:
```

**Comment by ndeloof** [comment]
@krzysieqq we still need to upgrade docker CLI to benefit the upstream fix

**Comment by krzysieqq** [comment]
@ndeloof Oh, I thought that I was updated already. Do you know when we can expect an update?

**Comment by nitzel** [comment]
> @krzysieqq not sure. A v23.x release is on his way, we should be able to upgrade to align with it

Does that mean the fix is live now? [Milesteon 23.0](https://github.com/docker/cli/milestone/51?closed=1) is closed 🥳

**Comment by jcandan** [comment]
Doesn't seem to be. I have Docker version `23.0.0` with docker-compose `v2.15.1`, and I am getting that same error:

```
error during connect: Post "http://docker.example.com/v1.42/images/create?fromImage=bitnami%2Fdrupal&tag=latest": command [ssh -l [MASKED] -- [MASKED] docker system dial-stdio] has exited with signal: killed, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=
```

when i run `docker-compose -H "ssh://$SERVER_USER@$SERVER_IP" pull` from my Gitlab pipeline.

Note: just previous to this, i am running `docker-compose -H "ssh://$SERVER_USER@$SERVER_IP" down --remove-orphans `, but not getting the error then.

**Comment by jcandan** [comment]
On a whim, I simplified my docker-compose to just a simple single container, and it worked. So, is this SSH error a red-herring?

**Comment by pdaig** [comment]
> Does that mean the fix is live now? [Milesteon 23.0](https://github.com/docker/cli/milestone/51?closed=1) is closed 🥳

@nitzel I don't think so... as I understand it, not yet but very soon.

I just tried it with the official v23.0 release and it's not fixed. The fix is live for docker/cli v23.0 but docker/compose v2.15.1 references an older version of docker/cli (v20.10.20). However, docker/compose v2.16 which was just released about 6 hours ago bumped that to v23. I guess depending on your installation method (Docker Desktop, OS package manager, image on Docker Hub) it might take more or less time for the new version to be distributed. I think Docker Hub is pretty fast to update but Docker Desktop might take a bit more time?

> On a whim, I simplified my docker-compose to just a simple single container, and it worked. So, is this SSH error a red-herring?

@jcandan v2.15.1 still has the bug so this is normal. 2 or more containers cause the issue, but 1 container is fine.

**Comment by pdaig** [comment]
Update:
`docker:23` has been updated on Docker Hub with compose v2.16. I can happily confirm the issue is fixed! 🥳

Docker Desktop and packages for Ubuntu/Debian/other OS should follow as well, but I don't have the update schedule.

**Comment by Dkhusainov** [comment]
```
Client: Docker Engine - Community
 Version:           23.0.4
 API version:       1.42
 Go version:        go1.19.8
 Git commit:        f480fb1
 Built:             Fri Apr 14 10:32:04 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.4
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.8
  Git commit:       cbce331
  Built:            Fri Apr 14 10:32:04 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.20
  GitCommit:        2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc:
  Version:          1.1.5
  GitCommit:        v1.1.5-0-gf19387a
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
I have this docker installed on my linux maching and still getting this error _sporadically_, maybe 70% of the time. The command I use:
```
docker context create my-context --docker "host=ssh://jenkins@1.1.1.1"
docker contest use my-context
docker compose --parallel 1 pull
```

Does anyone know If lower docker version on remote context causes the issue maybe? it's `20.10.7`

**Comment by pdaig** [comment]
> Does anyone know If lower docker version on remote context causes the issue maybe? it's `20.10.7`

I don't think the remote version matters in this case.
To my knowledge, it was strictly a client side issue in docker CLI. Docker Compose statically links to this package so it was affected as well.

Which version of docker compose do you have installed (`docker compose version`) ?
Have you tried updating it ?
Which OS are you using ?

I haven't tried with the `--parallel 1` flag thought. Maybe it could be that ?

**Comment by Dkhusainov** [comment]
>Which OS are you using ?

Tried both Windows and Linux.

> Which version of docker compose do you have installed (`

Docker Compose version v2.17.2

> I haven't tried with the --parallel 1 flag thought. Maybe it could be that ?

Same without parallel - `docker compose pull` gives me

```
error during connect: Get "http://docker.example.com/v1.41/images/registry.my.domain/devops/mailhog:1.0.0/json
``` 
every time with a different service

**Comment by pdaig** [comment]
I'm not able to reproduce the issue on my end (same version of docker server/client/compose).

The `error during connect` message can be caused by many things. Just to make sure, could you post the complete error message ?
If it's the same issue, the message should contain `has exited with signal: killed`.

Otherwise, it could be an issue with ssh/sshd or a network issue.

**Comment by Dkhusainov** [comment]
```
error during connect: Post "http://docker.example.com/v1.41/images/create?fromImage=registry.my.domain%2Fbackend%2Fbirt-generator&tag=latest": command [ssh -l **** -- api.release-01.oek.my.domain docker system dial-stdio] has exited with exit status 255, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=ssh_exchange_identification: read: Connection reset by peer
```

**Comment by pdaig** [comment]
I don't think it's the same issue.

The message you're getting says `has exited with exit status 255`, not `has exited with signal: killed`.
Also, the end of the message `ssh_exchange_identification: read: Connection reset by peer` seems to indicate an issue with the ssh server refusing the connection. It doesn't seems to be caused by docker. Maybe try to check your ssh settings, make sure the port isn't blocked and that you can establish a standard ssh session without docker.

Hope this helps
